<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * The shop's catalogue.
 *
 * Mobilier, Décoration and Salle de bain are the ranges we actually resell: names, prices and
 * photography come from the supplier's own catalogue (meuble-passion.com), so what a customer
 * sees on a product card is the piece that will be delivered. The photo files live in
 * seeders/assets/products as mp-<supplier id>.<ext> — named by supplier id rather than by slug
 * because several different products share a filename on the supplier's side.
 *
 * Jardin & Extérieur, Équipement Maison and Bois & Chauffage have no supplier feed yet and
 * therefore no photography. Product::thumbnail_url shows a neutral placeholder for them rather
 * than borrowing another item's picture.
 *
 * Descriptions are ours, not the supplier's: they open on what the piece is like to live with,
 * then give the specifics a buyer needs before ordering — dimensions, essence, finish, delivery.
 */
class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $mobilier = Category::where('slug', 'mobilier')->firstOrFail();
        $jardin = Category::where('slug', 'jardin-exterieur')->firstOrFail();
        $deco = Category::where('slug', 'decoration')->firstOrFail();
        $bain = Category::where('slug', 'salle-de-bain')->firstOrFail();
        $equipement = Category::where('slug', 'equipement-maison')->firstOrFail();
        $bois = Category::where('slug', 'bois-chauffage')->firstOrFail();

        $products = [
            // ================================================================ MOBILIER — Salon
            [
                'category_id' => $mobilier->id,
                'name' => 'Fauteuil confort vintage tissu et métal CHESTER 80 cm',
                'description' => "Le fauteuil bas dans lequel on s'enfonce, pas celui où l'on se tient droit. L'assise est profonde et légèrement inclinée vers l'arrière, le dossier capitonné retient les épaules : c'est un siège de fin de journée, à côté d'une lampe, et il se lève sans effort malgré la profondeur.\n\nLa structure apparente en métal noir tient l'ensemble sur quatre points seulement, ce qui allège visuellement une pièce déjà chargée. Le piétement luge répartit le poids et ne marque pas les parquets.\n\nDimensions : 80 x 85 x 78 cm, hauteur d'assise 42 cm. Tissu vintage, structure acier laqué noir, mousse haute résilience. Livré monté.",
                'price' => 250,
                'compare_at_price' => null,
                'colors' => ['Gris chiné', 'Brun cognac'],
                'stock' => 7,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['mp-12570.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Table basse bois recyclé coloré BOATWOOD 120 cm',
                'description' => "Le plateau est fait de bordages de bateaux de pêche indonésiens démontés : chaque planche garde sa peinture d'origine, bleue, turquoise, blanc écaillé, poncée juste assez pour être lisse sous la main sans effacer l'usure. Aucune table n'a la même composition de couleurs que la suivante.\n\nC'est la pièce qui donne le ton d'un salon entier. Posée devant un canapé uni, elle dispense de tout autre objet coloré dans la pièce.\n\nDimensions : 120 x 70 x 40 cm. Bois de bateau recyclé, piétement bois massif, finition cire mate. Pièce unique — les couleurs et le tracé des planches varient d'un exemplaire à l'autre. Livrée montée.",
                'price' => 690,
                'compare_at_price' => 790,
                'colors' => null,
                'stock' => 4,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['mp-8227.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Table basse cannage et teck ronde BOHO Ø 80 cm',
                'description' => "Une table basse ronde, donc sans angle sur lequel se cogner le tibia — la vraie raison pour laquelle on choisit un plateau rond dans un salon où l'on circule. Le fût central est habillé de cannage tressé main, ce qui allège une forme qui serait sinon massive.\n\nLe teck est huilé, pas verni : un verre posé sans dessous-de-verre laisse une auréole qui s'estompe d'elle-même en quelques jours.\n\nDimensions : Ø 80 cm, hauteur 40 cm. Teck massif et cannage de rotin tressé main, finition huile naturelle. Livrée montée.",
                'price' => 312,
                'compare_at_price' => 390,
                'colors' => null,
                'stock' => 6,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-12987.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Meuble TV en cannage et teck BOHO 160 cm',
                'description' => "Cent soixante centimètres, c'est la longueur qui permet enfin de ne pas voir dépasser le téléviseur de part et d'autre du meuble. Deux portes en cannage tressé cachent les boîtiers, deux niches ouvertes laissent respirer la barre de son et passer l'infrarouge des télécommandes.\n\nLe cannage n'est pas décoratif seulement : il ventile. Un décodeur enfermé derrière une porte pleine chauffe ; derrière du rotin tressé, non.\n\nDimensions : 160 x 40 x 50 cm. Teck massif et cannage de rotin tressé main, finition huile naturelle. Deux portes, deux niches ouvertes, passe-câbles à l'arrière. Livré monté.",
                'price' => 790,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 5,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['mp-12994.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Bibliothèque scandinave chêne massif huilé OSLO 90 cm',
                'description' => "Quatre étagères ouvertes au-dessus, deux tiroirs pleins en dessous : ce qui se montre reste visible, ce qui traîne disparaît. C'est la répartition qui fait qu'une bibliothèque de salon reste présentable sans qu'on ait à la ranger tous les jours.\n\nLe chêne est massif sur toutes les faces, y compris les montants et le fond — pas de panneau de particules plaqué à l'arrière, ce qui compte pour un meuble qu'on voit parfois de trois quarts.\n\nDimensions : 90 x 40 x 190 cm. Chêne massif huilé, quatre niches, deux tiroirs sur coulisses. Fixation antibascule fournie. Livrée montée.",
                'price' => 1490,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 3,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-12718.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Bibliothèque colonne industrielle teck recyclé SALVADOR 80 cm',
                'description' => "Une colonne étroite pour les murs où il ne reste que quatre-vingts centimètres — entre une porte et un angle, au bout d'un couloir. Elle monte plutôt qu'elle ne s'étale, et libère au sol la place d'un fauteuil.\n\nLe teck recyclé provient de charpentes et d'huisseries anciennes : les trous de cheville et les fentes de séchage ont été laissés visibles. Le contraste avec le métal noir des montants est le sujet du meuble.\n\nDimensions : 80 x 40 x 180 cm. Teck massif recyclé et acier laqué noir, finition cire mate. Trois niches ouvertes, deux tiroirs. Livrée montée.",
                'price' => 1090,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 3,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-13979.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Bout de canapé chêne massif 1 tiroir OSLO 30 cm',
                'description' => "Trente centimètres de côté : la place d'une tasse, d'un livre et d'une lampe, et rien de plus — c'est exactement ce qu'on demande à un bout de canapé. Sa hauteur est calée sur celle d'un accoudoir standard, donc on pose sans lever le bras.\n\nLe tiroir avale les télécommandes et les lunettes, la tablette basse le magazine en cours. Deux rangements suffisent à ce qu'il ne devienne jamais un dépotoir.\n\nDimensions : 30 x 30 x 60 cm. Chêne massif huilé, un tiroir, une tablette basse. Livré monté.",
                'price' => 290,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 9,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['mp-11620.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Bout de canapé rond racine de teck RACINE Ø 40 cm',
                'description' => "Une souche de teck arrachée après abattage, séchée deux ans, puis simplement tranchée à plat en haut et en bas. Tout le reste — les creux, les nœuds, le réseau de racines — est laissé tel quel. C'est un objet qu'on choisit pour sa forme, pas pour sa fonction, même s'il tient parfaitement un plateau.\n\nAucune pièce ne ressemble à une autre. La photo montre l'esprit de la sélection, pas l'exemplaire exact qui sera expédié.\n\nDimensions : environ Ø 40 cm, hauteur 45 cm (variables). Racine de teck massive, finition cire incolore. Pièce unique. Poids 15 à 25 kg selon la souche.",
                'price' => 120,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 8,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-12675.jpg'],
            ],

            // ============================================================== MOBILIER — Chambre
            [
                'category_id' => $mobilier->id,
                'name' => 'Lit chêne massif OSLO 160 x 200 cm',
                'description' => "Une tête de lit basse et pleine, des pieds fuselés, et plus rien : ce lit ne cherche pas à occuper la chambre. C'est ce qui le rend facile à vivre dans une pièce de taille moyenne, où un lit à cadre haut mange visuellement tout le sol.\n\nLe sommier à lattes est inclus et se pose directement dans le cadre — pas de sommier tapissier à acheter en plus, et vingt centimètres de hauteur gagnés.\n\nDimensions : couchage 160 x 200 cm, encombrement 172 x 212 x 90 cm. Chêne massif huilé, sommier à lattes massives inclus. Matelas non fourni. Livré à plat, montage à deux en 30 minutes.",
                'price' => 1350,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 3,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['mp-11967.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Grand lit chêne massif OSLO 180 x 200 cm',
                'description' => "Le même lit que le 160, vingt centimètres plus large. Ces vingt centimètres sont la différence entre dormir à deux et dormir chacun de son côté sans se réveiller quand l'autre se retourne — la seule raison valable de passer au 180.\n\nVérifiez la largeur de porte et de palier avant de commander : le cadre monté ne se démonte pas facilement une fois en place.\n\nDimensions : couchage 180 x 200 cm, encombrement 192 x 212 x 90 cm. Chêne massif huilé, sommier à lattes massives inclus. Matelas non fourni. Livré à plat.",
                'price' => 1450,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 3,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-12687.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Lit double suar et teck massif SAMANEA 160 x 200 cm',
                'description' => "Le suar est un bois tropical à gros veinage, beaucoup plus contrasté que le chêne : des bruns profonds traversés de veines claires, parfois presque noires. Associé au teck des montants, il donne un lit qui se voit — l'inverse exact du parti pris scandinave.\n\nLe cadre est lourd, et c'est voulu : un lit massif de cette masse ne grince pas et ne se déplace pas dans la nuit.\n\nDimensions : couchage 160 x 200 cm. Suar et teck massifs, finition cire naturelle, sommier à lattes inclus. Matelas non fourni. Le veinage varie d'un exemplaire à l'autre. Livré à plat.",
                'price' => 1490,
                'compare_at_price' => 1690,
                'colors' => null,
                'stock' => 2,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-6166.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Table de chevet chêne massif OSLO 30 cm',
                'description' => "Étroite exprès. Trente centimètres de large, c'est ce qui passe entre un lit et un mur sans obliger à décaler le matelas, et c'est assez pour une lampe, un verre d'eau et un livre.\n\nLe tiroir supérieur est court et haut — pensé pour ce qu'on range vraiment à côté d'un lit — et la tablette basse reçoit la pile de livres en attente.\n\nDimensions : 30 x 30 x 60 cm. Chêne massif huilé, un tiroir, une tablette basse. S'accorde au lit OSLO. Livrée montée.",
                'price' => 250,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 12,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['mp-11542.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Chevet moderne chêne massif cannelé HOUSTON 50 cm',
                'description' => "La façade est cannelée dans la masse — des gorges verticales taillées dans le chêne, pas un placage rapporté. La lumière rasante d'une lampe de chevet y crée une alternance d'ombres qui change selon l'heure ; c'est un meuble qui a l'air différent le matin et le soir.\n\nLa niche ouverte reçoit le livre en cours, le tiroir ce qu'on ne veut pas voir. Pas de poignée : la façade se pousse.\n\nDimensions : 50 x 40 x 55 cm. Chêne massif cannelé, finition huile naturelle. Un tiroir push-pull, une niche. Livré monté.",
                'price' => 330,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 8,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['mp-14067.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Chevet bois recyclé vintage MERAKI 45 cm',
                'description' => "Construit en bois de récupération : des planches d'anciens meubles et de charpentes, assemblées avec leurs différences de teinte assumées. Une façade peut être plus claire que le côté, une planche porter encore un ancien trou de vis. C'est le principe, pas un défaut.\n\nPosé à côté d'un lit très sobre, il apporte la seule irrégularité de la chambre — souvent tout ce qui manquait.\n\nDimensions : 45 x 35 x 55 cm. Bois massif recyclé sur piétement métal, finition cire mate. Un tiroir. Aspect et teintes variables d'un exemplaire à l'autre. Livré monté.",
                'price' => 190,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 10,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-12286.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Commode scandinave chêne massif huilé OSLO 110 cm 4 tiroirs',
                'description' => "Quatre grands tiroirs pleine largeur, sans séparation : de quoi ranger par catégorie plutôt que par taille de compartiment. Les deux du bas sont plus profonds, pour les pulls et les draps qui ne rentrent nulle part ailleurs.\n\nLes tiroirs sont montés sur coulisses à sortie totale — on atteint le fond sans avoir à vider le devant, ce qui est la seule chose qui distingue vraiment une bonne commode d'une commode ordinaire.\n\nDimensions : 110 x 45 x 80 cm. Chêne massif huilé, quatre tiroirs sur coulisses à sortie totale. Fixation antibascule fournie. Livrée montée.",
                'price' => 1190,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['mp-12746.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Commode en cannage et teck BOHO 6 tiroirs',
                'description' => "Six tiroirs à façade de cannage tressé, sur trois rangs. Le tressage laisse deviner ce qu'il y a derrière sans le montrer — la commode reste légère à l'œil malgré son volume, ce qu'aucune façade pleine ne permet.\n\nLe format à six tiroirs répartit mieux qu'une commode à quatre : chaussettes, sous-vêtements, tee-shirts trouvent chacun leur tiroir sans se mélanger.\n\nDimensions : 100 x 40 x 90 cm. Teck massif et cannage de rotin tressé main, finition huile naturelle. Six tiroirs. Livrée montée.",
                'price' => 690,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 5,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-13028.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Petite armoire scandinave chêne massif huilé OSLO h 145 cm',
                'description' => "Cent quarante-cinq centimètres seulement : elle passe sous une sous-pente, dans une chambre mansardée ou une chambre d'amis où une armoire pleine hauteur serait absurde. La penderie intérieure accepte des vestes et des robes courtes ; les deux tiroirs du bas prennent le reste.\n\nÀ cette hauteur, le dessus devient une surface utile — c'est là qu'atterrissent la lampe et le vase, et l'armoire cesse d'être un bloc.\n\nDimensions : 90 x 55 x 145 cm. Chêne massif huilé, deux portes, penderie intérieure, deux tiroirs. Fixation antibascule fournie. Livrée montée.",
                'price' => 1590,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 2,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-12706.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Armoire en cannage et teck BOHO 120 cm',
                'description' => "Deux portes entièrement habillées de cannage tressé main, sur toute leur hauteur. C'est une armoire qui ventile : le linge enfermé derrière du rotin ne prend pas l'odeur de renfermé des armoires à portes pleines, ce qui compte dans une chambre peu chauffée ou une maison de campagne.\n\nLe volume intérieur est simple — une penderie, une étagère haute, deux tiroirs — et c'est suffisant.\n\nDimensions : 120 x 60 x 200 cm. Teck massif et cannage de rotin tressé main, finition huile naturelle. Penderie, étagère, deux tiroirs. Fixation antibascule fournie. Livrée montée.",
                'price' => 1290,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 2,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-13292.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Tête de lit mosaïque bois MOZAIK 160 cm',
                'description' => "Une mosaïque de petits cabochons de bois recyclé, chacun d'une teinte différente : ocre, vert délavé, bleu ancien, brun. Vue de loin, l'ensemble fait une seule surface chaude ; de près, on distingue chaque pièce et l'ancienne peinture qu'elle porte.\n\nC'est le moyen le plus rapide de donner un caractère à une chambre blanche sans y ajouter un seul autre objet. Elle se fixe au mur, indépendamment du lit, ce qui permet de garder le lit qu'on a déjà.\n\nDimensions : 160 x 5 x 120 cm, pour un couchage en 160. Bois recyclé sur cadre massif, finition cire mate. Fixations murales fournies. Composition unique à chaque exemplaire.",
                'price' => 450,
                'compare_at_price' => 550,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-11550.jpg'],
            ],

            // =============================================================== MOBILIER — Bureau
            [
                'category_id' => $mobilier->id,
                'name' => 'Bureau chêne massif moderne 2 tiroirs OSLO 137 cm',
                'description' => "Cent trente-sept centimètres de plateau, deux tiroirs suspendus sous le plan, et des pieds fuselés qui dégagent complètement le dessous : on peut y glisser une chaise, un caisson ou simplement ses jambes en travers.\n\nLes tiroirs sont peu profonds, ce qui les empêche de devenir des tiroirs fourre-tout. Assez pour un carnet, des câbles et un chargeur, pas assez pour six mois de courrier non ouvert.\n\nDimensions : 137 x 60 x 76 cm. Chêne massif huilé, deux tiroirs. Passe-câble arrière. Livré à plat, montage 20 minutes.",
                'price' => 690,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 5,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['mp-12704.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Bureau chêne massif huilé OAKWOOD 130 cm',
                'description' => "Un bureau à caisson, dans la tradition du bureau de notaire : trois tiroirs d'un côté, un plan de travail dégagé de l'autre. La différence avec un bureau plat est qu'on y range vraiment — dossiers debout dans le tiroir profond du bas, petites fournitures au-dessus.\n\nLe chêne huilé prend la lumière sans réfléchir : pas de reflet de fenêtre en travers d'un écran, ce que le vernis brillant ne pardonne jamais.\n\nDimensions : 130 x 65 x 78 cm. Chêne massif huilé, caisson trois tiroirs. Livré monté.",
                'price' => 790,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-215.png'],
            ],

            // =================================================== MOBILIER — Étagères murales
            [
                'category_id' => $mobilier->id,
                'name' => '3 étagères murales cube bois massif OSLO',
                'description' => "Trois cubes ouverts à fixer où l'on veut : alignés au-dessus d'un bureau, décalés en escalier dans une cage d'escalier, ou empilés en colonne dans un angle. La composition se décide au mur, pas à l'achat.\n\nLe fond est plein et en bois massif comme le reste : posés contre un mur peint sombre, les cubes gardent leur propre couleur au lieu de laisser apparaître le mur.\n\nDimensions : 3 cubes de 30 x 20 x 30 cm. Chêne massif huilé. Fixations murales invisibles fournies, pour mur plein. Charge conseillée 8 kg par cube.",
                'price' => 290,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 11,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-11798.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Étagère murale industrielle bois recyclé TUAREG ronde',
                'description' => "Un cercle de métal noir traversé de deux plateaux de bois recyclé. Accrochée seule sur un grand mur nu, elle fait office de tableau autant que de rangement — c'est le genre de pièce qu'on choisit pour la forme et qui rend service par accident.\n\nLes plateaux sont assez profonds pour des livres posés à plat et des objets, pas pour des livres debout de poche qui basculeraient.\n\nDimensions : Ø 60 cm, profondeur 20 cm. Bois de teck recyclé et acier laqué noir. Fixations murales fournies. Charge conseillée 10 kg.",
                'price' => 345,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 6,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-8428.jpg'],
            ],
            [
                'category_id' => $mobilier->id,
                'name' => 'Étagère à vin murale SHELFMATE 65 cm teck et métal recyclés',
                'description' => "Les bouteilles sont couchées, col vers l'extérieur, sur deux niveaux : le bouchon reste en contact avec le vin, ce qui est la seule condition qui compte pour garder une bouteille debout plus de quelques semaines.\n\nFixée au mur, elle libère le plan de travail et transforme six bouteilles en décoration murale. Le teck recyclé et le métal noir vont aussi bien dans une cuisine que dans une salle à manger.\n\nDimensions : 65 x 20 x 35 cm, capacité 6 bouteilles standard. Teck massif recyclé et acier laqué noir. Fixations murales fournies, pour mur plein.",
                'price' => 122.55,
                'compare_at_price' => 145,
                'colors' => null,
                'stock' => 14,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-3280.jpg'],
            ],

            // ==================================================================== DÉCORATION
            [
                'category_id' => $deco->id,
                'name' => 'Miroir racine de teck RACINE',
                'description' => "Le cadre est une seule tranche de racine de teck, découpée puis évidée pour recevoir le verre. Les vides, les nœuds et les entrelacs sont ceux qu'a formés l'arbre : rien n'a été sculpté ni ajouté.\n\nAccroché dans une entrée, il fait davantage qu'agrandir la pièce — il tient lieu d'unique objet sur le mur, et c'est suffisant.\n\nDimensions : environ Ø 90 cm, épaisseur 6 cm (variables). Racine de teck massive, finition cire incolore, miroir clair 4 mm. Pièce unique : le tracé du cadre diffère à chaque exemplaire. Fixation murale renforcée fournie.",
                'price' => 350,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 6,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['mp-5076.jpg'],
            ],
            [
                'category_id' => $deco->id,
                'name' => 'Miroir chêne huilé OAKWOOD 110 x 80 cm',
                'description' => "Un rectangle de chêne massif, un verre, rien d'autre. Le format 110 x 80 est celui qui fonctionne à la fois au-dessus d'une console d'entrée et à la verticale dans une chambre — il s'accroche dans les deux sens.\n\nLe cadre a quatre centimètres d'épaisseur, assez pour porter une ombre nette sur le mur et détacher le miroir au lieu de le laisser s'y fondre.\n\nDimensions : 110 x 80 cm, cadre 4 cm. Chêne massif huilé, miroir clair 4 mm. Accrochage horizontal ou vertical, fixations fournies.",
                'price' => 210,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 9,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-227.png'],
            ],
            [
                'category_id' => $deco->id,
                'name' => 'Miroir teck recyclé brossé POHON',
                'description' => "Le teck a été brossé à la brosse métallique : les fibres tendres sont creusées, les fibres dures ressortent, et la surface prend un relief qu'on sent sous le doigt. La finition blanchie laisse le grain apparaître par transparence.\n\nC'est le miroir des intérieurs clairs, où un cadre en bois brut ferait une tache trop chaude.\n\nDimensions : environ 120 x 80 cm, cadre 8 cm. Teck massif recyclé brossé, finition blanchie, miroir clair 4 mm. Les fentes et trous de cheville du bois ancien sont conservés. Fixations fournies.",
                'price' => 310,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 5,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-5150.jpg'],
            ],
            [
                'category_id' => $deco->id,
                'name' => 'Miroir en bambou rond RATTAN 60 cm',
                'description' => "Un soleil de brins de bambou rayonnant autour d'un miroir rond. C'est l'objet à moins de quarante euros qui change une pièce : au-dessus d'une commode, dans un couloir, dans une chambre d'enfant, il apporte un motif là où il n'y en avait aucun.\n\nTrès léger, il tient sur un simple clou — pas besoin de cheville à expansion ni de perceuse.\n\nDimensions : Ø 60 cm au total, miroir Ø 25 cm. Bambou naturel et miroir 3 mm. Poids 1,2 kg. Attache au dos.",
                'price' => 32,
                'compare_at_price' => 45,
                'colors' => null,
                'stock' => 30,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['mp-10767.jpg'],
            ],
            [
                'category_id' => $deco->id,
                'name' => 'Décoration murale bois de bateau BOATWOOD 100 cm — Matahari',
                'description' => "Un panneau composé de planches de bateaux de pêche démontés, disposées en rayons autour d'un centre — matahari veut dire soleil en indonésien. Les couleurs sont celles des coques : bleus délavés, rouges passés, blancs écaillés par le sel.\n\nAccroché seul sur un mur clair, il remplace un tableau et fonctionne dans les pièces où l'on n'aurait pas su quoi mettre.\n\nDimensions : 100 x 100 x 5 cm. Bois de bateau recyclé sur cadre massif, finition cire mate. Chaque panneau est unique. Fixations murales renforcées fournies.",
                'price' => 390,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-7269.jpg'],
            ],
            [
                'category_id' => $deco->id,
                'name' => 'Décoration murale bois de bateau BOATWOOD 100 cm — Patchwork',
                'description' => "La même matière que le panneau Matahari, mais assemblée en bandes verticales irrégulières plutôt qu'en rayons : des bleus profonds, des verts d'eau, quelques planches restées brutes. Le résultat est plus calme, plus proche d'un aplat de couleur.\n\nDeux panneaux côte à côte tiennent un grand mur de salon sans qu'il faille rien ajouter.\n\nDimensions : 100 x 100 x 5 cm. Bois de bateau recyclé sur cadre massif, finition cire mate. Composition unique à chaque exemplaire. Fixations murales renforcées fournies.",
                'price' => 253.50,
                'compare_at_price' => 310,
                'colors' => null,
                'stock' => 5,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-7277.jpg'],
            ],
            [
                'category_id' => $deco->id,
                'name' => 'Statue bouddha assis BUDDHA GRC terracotta h 120 cm',
                'description' => "Un mètre vingt assis : c'est la taille à partir de laquelle une statue cesse d'être un objet posé et devient un élément de la pièce. Moulée en GRC — béton fibré de verre — dans une teinte terracotta mate qui imite la terre cuite ancienne.\n\nLe GRC supporte le gel et la pluie : cette statue vit aussi bien au fond d'un jardin ou près d'un bassin que dans une véranda.\n\nDimensions : 75 x 55 x 120 cm, poids environ 60 kg. GRC teinté dans la masse, finition terracotta vieillie. Utilisation intérieure ou extérieure. Livraison sur rendez-vous, dépose au pied de la propriété.",
                'price' => 490,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 3,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-9647.jpg'],
            ],
            [
                'category_id' => $deco->id,
                'name' => 'Statuette bois ancien Ganesh h 46 cm',
                'description' => "Sculptée dans une pièce de bois ancien récupérée en Inde, à la gouge, sans ponçage final : les traces d'outil restent visibles sur tout le dos de la statuette, et c'est ce qui la distingue d'un moulage.\n\nQuarante-six centimètres, c'est la hauteur qui fonctionne sur une console ou une cheminée sans qu'il faille lui dégager toute la surface.\n\nDimensions : environ 20 x 15 x 46 cm. Bois massif ancien sculpté main, finition cire naturelle. Pièce unique — les traits et les fentes du bois varient d'un exemplaire à l'autre.",
                'price' => 290,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 5,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-14769.jpg'],
            ],
            [
                'category_id' => $deco->id,
                'name' => 'Statue éléphant bois INDIA h 32 cm',
                'description' => "Sculpté puis peint à la main, caparaçonné de rouge, d'or et de bleu comme les éléphants de fête du Rajasthan. La peinture est appliquée motif par motif : en s'approchant, on voit que rien ne se répète exactement d'un côté à l'autre.\n\nPetit format, donc facile à placer — une étagère, un rebord de fenêtre, le haut d'une bibliothèque. C'est souvent le premier objet indien qu'on achète, et rarement le dernier.\n\nDimensions : environ 30 x 15 x 32 cm. Bois massif sculpté et peint main, finition vernis mat. Chaque pièce est unique.",
                'price' => 150,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 12,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['mp-14778.jpg'],
            ],

            // ================================================================= SALLE DE BAIN
            [
                'category_id' => $bain->id,
                'name' => 'Meuble salle de bain teck massif GARIS 60 cm',
                'description' => "Soixante centimètres, un plan et une tablette basse ouverte : le meuble des petites salles d'eau et des lave-mains d'invités, où un caisson fermé serait trop lourd.\n\nLe teck est le bois de la salle de bain. Ses huiles naturelles le rendent insensible à l'humidité permanente qui fait gonfler et cloquer n'importe quel panneau mélaminé au bout de deux ou trois ans. Celui-ci n'est ni verni ni plaqué : massif sur toutes ses faces.\n\nDimensions : 60 x 45 x 80 cm. Teck massif huilé, une tablette basse. Vasque et robinetterie non fournies. Livré monté.",
                'price' => 350,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 6,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-15467.jpg'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Meuble salle de bain suspendu teck massif MANDI 80 cm',
                'description' => "Suspendu, donc le sol reste entièrement dégagé : on passe la serpillière d'un seul geste sous le meuble, et la pièce paraît plus grande qu'elle ne l'est. C'est le seul vrai argument du meuble suspendu, et il suffit.\n\nQuatre tiroirs à façade lisse, sans poignée, qui s'ouvrent à la pression. Le teck massif est huilé et supportera la vapeur quotidienne d'une douche sans se déformer.\n\nDimensions : 80 x 45 x 50 cm. Teck massif huilé, quatre tiroirs push-pull sur coulisses. Fixations murales renforcées fournies — mur porteur requis. Vasque et robinetterie non fournies.",
                'price' => 450,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 5,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['mp-16186.webp'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Meuble suspendu salle de bain teck massif MANDI 120 cm',
                'description' => "Cent vingt centimètres, c'est la largeur qui permet une vasque décentrée et un vrai plan libre à côté — l'endroit où poser ce qu'on utilise le matin sans devoir le ranger à chaque fois.\n\nDeux tiroirs et deux niches ouvertes : les serviettes roulées restent visibles et à portée, le reste disparaît. Teck massif huilé sur toutes les faces, y compris le dessous, qui est la partie qui prend le plus d'humidité.\n\nDimensions : 120 x 45 x 50 cm. Teck massif huilé, deux tiroirs, deux niches. Fixations murales renforcées fournies — mur porteur requis. Vasque et robinetterie non fournies.",
                'price' => 690,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 4,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-16211.webp'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Meuble suspendu salle de bain teck massif MANDI 150 cm',
                'description' => "Le format double vasque, ou simple vasque avec un très grand plan libre. Cent cinquante centimètres, c'est ce qui met fin aux négociations du matin dans une salle de bain partagée.\n\nQuatre tiroirs et deux niches ouvertes se répartissent de part et d'autre. Le meuble est lourd une fois monté : la fixation murale fournie est dimensionnée en conséquence, mais un mur porteur est indispensable.\n\nDimensions : 150 x 45 x 50 cm. Teck massif huilé, quatre tiroirs, deux niches. Fixations murales renforcées fournies — mur porteur requis. Vasques et robinetterie non fournies.",
                'price' => 850,
                'compare_at_price' => 950,
                'colors' => null,
                'stock' => 3,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-16202.webp'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Meuble salle de bain cannage et teck massif BOHO 90 cm',
                'description' => "Deux portes en cannage tressé main plutôt que des façades pleines : l'air circule en permanence dans le caisson, et les serviettes rangées humides sèchent au lieu de sentir le renfermé. Dans une salle de bain, c'est un avantage concret, pas seulement une allure.\n\nPosé au sol sur quatre pieds, il se nettoie tout autour et supporte les sols qui ne sont pas parfaitement plans.\n\nDimensions : 90 x 45 x 80 cm. Teck massif et cannage de rotin tressé main, finition huile naturelle. Deux portes, une étagère intérieure. Vasque et robinetterie non fournies. Livré monté.",
                'price' => 590,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['mp-12934.jpg'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Miroir salle de bain teck MANDI 80 cm avec tablette',
                'description' => "Un miroir avec une tablette intégrée à sa base : brosse à dents, savon, bague qu'on retire pour se laver les mains trouvent leur place sans encombrer le plan de la vasque.\n\nLe cadre est en teck massif huilé, la même essence et la même finition que les meubles MANDI — l'ensemble se répond sans effet de série puisque chaque pièce garde son propre veinage.\n\nDimensions : 80 x 12 x 70 cm, tablette profondeur 12 cm. Teck massif huilé, miroir clair 4 mm. Fixations murales fournies.",
                'price' => 250,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 8,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-16234.webp'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Miroir salle de bain teck MANDI 120 cm avec tablette',
                'description' => "La version large, à assortir aux meubles de 120 ou 150 cm. Au-delà d'un mètre, un miroir cesse de renvoyer un visage et renvoie la pièce : une petite salle de bain paraît doubler de surface.\n\nMême construction que le 80 cm — cadre en teck massif huilé et tablette basse intégrée sur toute la largeur.\n\nDimensions : 120 x 12 x 70 cm, tablette profondeur 12 cm. Teck massif huilé, miroir clair 4 mm. Fixations murales fournies.",
                'price' => 350,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 6,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-16244.webp'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Étagère murale salle de bain teck massif MANDI 80 cm',
                'description' => "Trois cases de tailles différentes dans un cadre en teck massif. Les flacons hauts tiennent debout dans la grande, les petits objets restent visibles dans les deux autres — c'est l'inverse de l'étagère à hauteur unique où tout finit couché.\n\nÀ fixer au-dessus des toilettes ou dans l'angle qu'on ne sait jamais comment occuper.\n\nDimensions : 80 x 15 x 60 cm. Teck massif huilé, trois niches. Fixations murales fournies, pour mur plein. Charge conseillée 12 kg.",
                'price' => 152,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 10,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-16247.webp'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Vasque galet à poser STONE 40-50 cm',
                'description' => "Un galet de rivière évidé. L'extérieur garde la surface polie par l'eau pendant des siècles ; seul l'intérieur a été creusé et lissé. Chaque vasque a donc une forme, une taille et une couleur qui lui sont propres — gris, beige, veiné de sombre.\n\nÀ poser sur un plan de teck, elle devient l'objet qu'on regarde en entrant dans la pièce. Prévoir une robinetterie haute, en applique murale ou sur bec long.\n\nDimensions : environ 40 à 50 cm dans sa plus grande largeur, hauteur 15 cm. Pierre naturelle, intérieur poli et traité hydrofuge. Bonde standard 40 mm. Pièce unique. Poids 15 à 25 kg.",
                'price' => 140,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 9,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['mp-5774.jpg'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Lave-mains galet à poser STONE 30-40 cm',
                'description' => "Le même galet évidé, en format réduit : trente à quarante centimètres, la taille qui convient à un lave-mains de WC ou d'entrée où une vasque pleine grandeur ne rentrerait pas.\n\nMalgré sa taille, c'est une pierre pleine : comptez une dizaine de kilos et un support qui les supporte.\n\nDimensions : environ 30 à 40 cm dans sa plus grande largeur, hauteur 12 cm. Pierre naturelle, intérieur poli et traité hydrofuge. Bonde standard 40 mm. Pièce unique. Poids 8 à 15 kg.",
                'price' => 120,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 11,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['mp-5775.jpg'],
            ],
            [
                'category_id' => $bain->id,
                'name' => 'Vasque à poser marbre ronde STONE martelée',
                'description' => "Un bol de marbre parfaitement rond à l'intérieur, martelé à la main à l'extérieur. Le contraste entre les deux surfaces est tout le sujet : la paume glisse sur le poli et accroche sur le martelé.\n\nLe marbre est une pierre calcaire, donc sensible aux acides : un détartrant classique la mate définitivement. Un savon neutre et un chiffon suffisent, et c'est le seul entretien qu'elle demande.\n\nDimensions : Ø 40 cm, hauteur 15 cm. Marbre naturel, intérieur poli et traité hydrofuge, extérieur martelé main. Bonde standard 40 mm. Veinage unique. Poids environ 12 kg.",
                'price' => 120,
                'compare_at_price' => 150,
                'colors' => null,
                'stock' => 7,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['mp-6000.jpg'],
            ],

            // ============================================================ JARDIN & EXTÉRIEUR
            [
                'category_id' => $jardin->id,
                'name' => 'Table de jardin Teck massif 180 cm',
                'description' => "Le teck est le seul bois qu'on peut laisser dehors toute l'année sans y penser : sa densité et ses huiles naturelles le protègent seuls. Cette table prendra une patine gris argenté en une ou deux saisons — la teinte qu'on voit sur les terrasses de bord de mer. Si vous préférez le miel du premier jour, un huilage par an suffit à le retenir.\n\nLes assemblages sont chevillés, pas vissés : aucune vis ne rouillera à cœur au bout de cinq hivers.\n\nDimensions : 180 x 90 x 75 cm, six convives. Teck massif d'origine contrôlée. Reste dehors toute l'année.",
                'price' => 890,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 4,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => [],
            ],
            [
                'category_id' => $jardin->id,
                'name' => 'Fauteuil de jardin Teck et corde',
                'description' => "L'assise est tressée en corde marine, main. C'est ce qui change tout après une averse : l'eau traverse, la corde sèche en une heure, et on se rassoit sans aller chercher un coussin trempé au fond du garage.\n\nBas, légèrement incliné vers l'arrière, c'est un fauteuil de fin d'après-midi plus qu'un siège de repas. Il s'empile par deux pour l'hiver.\n\nDimensions : 70 x 75 x 78 cm. Structure teck massif, corde polypropylène tressée main, traitée anti-UV.",
                'price' => 420,
                'compare_at_price' => null,
                'colors' => ['Corde écrue', 'Corde anthracite'],
                'stock' => 8,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => [],
            ],
            [
                'category_id' => $jardin->id,
                'name' => 'Banc de jardin Teck 150 cm',
                'description' => "Un banc sans dossier, qu'on pousse contre un mur chaud ou qu'on laisse au bout de l'allée. Deux personnes largement, trois en se serrant. Sa vraie qualité est de ne pas avoir d'avant ni d'arrière : on s'y assoit du côté d'où l'on vient.\n\nTeck massif non traité, qui grisera comme la table de jardin assortie.\n\nDimensions : 150 x 40 x 45 cm. Teck massif d'origine contrôlée, assemblages chevillés. Reste dehors toute l'année.",
                'price' => 590,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 5,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => [],
            ],

            // ============================================================= ÉQUIPEMENT MAISON
            [
                'category_id' => $equipement->id,
                'name' => 'Portemanteau mural Chêne 5 patères',
                'description' => "Une barre de chêne massif et cinq patères tournées, espacées assez largement pour qu'un manteau d'hiver n'écrase pas celui d'à côté — le défaut de presque tous les portemanteaux muraux.\n\nSe visse dans deux points seulement, mais tient une charge réelle : la barre est pleine, pas plaquée.\n\nDimensions : 60 x 6 x 10 cm, cinq patères. Chêne massif, finition huile naturelle. Chevilles pour mur plein fournies.",
                'price' => 89,
                'compare_at_price' => null,
                'colors' => ['Chêne naturel', 'Chêne fumé'],
                'stock' => 18,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => [],
            ],
            [
                'category_id' => $equipement->id,
                'name' => 'Escabeau Bois et métal 3 marches',
                'description' => "Assez beau pour rester dehors, ce qui est tout l'enjeu d'un escabeau : celui qu'on range finit au fond d'un placard, et on monte sur une chaise. Marches en hêtre massif, structure acier laqué, et une fois replié il tient contre un mur sur cinq centimètres d'épaisseur.\n\nLa dernière marche est assez large pour y tenir des deux pieds sans chercher l'équilibre.\n\nDimensions : 45 x 50 x 90 cm déplié, 5 cm d'épaisseur replié. Marches hêtre massif, structure acier laqué noir. Charge maximale 120 kg.",
                'price' => 140,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 11,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => [],
            ],
            [
                'category_id' => $equipement->id,
                'name' => 'Panier de rangement Jonc tressé',
                'description' => "Le panier où finit tout ce qui n'a pas de place : les plaids du salon, les jouets du soir, le linge à plier. Tressé en jonc de mer, il garde sa forme une fois vide au lieu de s'affaisser — c'est la seule chose qu'on demande vraiment à un panier.\n\nDeux anses cousues permettent de le déplacer chargé.\n\nDimensions : 45 cm de diamètre, 40 cm de haut. Jonc de mer tressé main, anses coton. Se vide et s'aspire ; ne pas laver à l'eau.",
                'price' => 55,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 26,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => [],
            ],

            // ============================================================== BOIS & CHAUFFAGE
            [
                'category_id' => $bois->id,
                'name' => 'Bûches de chêne 50 cm — 1 stère',
                'description' => "Du chêne fendu, séché deux ans sous abri ventilé. C'est la braise longue : celle qui tient encore le matin et qu'on relance d'une bûche au lieu de rallumer un feu.\n\nNous mesurons l'humidité avant chaque expédition et n'expédions pas au-dessus de 20 %. Ce n'est pas un détail de fiche technique : un bois trop humide chauffe moitié moins, encrasse le conduit et vous fait ramoner deux fois plus souvent.\n\nQuantité : 1 stère. Chêne français, séchage naturel 24 mois, humidité inférieure à 20 %. Livré sur palette, déchargement au pied de la propriété, sur rendez-vous.",
                'price' => 89,
                'compare_at_price' => null,
                'sizes' => ['Bûches 33 cm', 'Bûches 50 cm'],
                'colors' => null,
                'stock' => 40,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => [],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Bûches de hêtre 33 cm — 1 stère',
                'description' => "Le hêtre monte en température plus vite que le chêne et donne une flamme plus vive. C'est le bois des soirées où l'on veut que la pièce soit chaude tout de suite, et le format qui convient aux poêles et aux inserts à petite chambre de combustion.\n\nMême exigence de séchage que notre chêne : deux ans sous abri, humidité contrôlée avant départ.\n\nQuantité : 1 stère. Hêtre français, séchage naturel 24 mois, humidité inférieure à 20 %. Livré sur palette, déchargement au pied de la propriété.",
                'price' => 95,
                'compare_at_price' => null,
                'sizes' => ['Bûches 33 cm', 'Bûches 50 cm'],
                'colors' => null,
                'stock' => 35,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => [],
            ],
            [
                'category_id' => $bois->id,
                'name' => "Filet de bois d'allumage 10 kg",
                'description' => "De quoi allumer une trentaine de feux sans journal froissé ni cube chimique. Du petit bois de résineux, sec, calibré court : deux poignées croisées, une allumette, et le feu prend seul pendant qu'on fait autre chose.\n\nLe filet se referme, donc le reste ne se répand pas dans le garage.\n\nQuantité : filet refermable de 10 kg. Résineux séché, longueur 20 à 25 cm, humidité inférieure à 18 %. Expédié en colis standard.",
                'price' => 19,
                'compare_at_price' => 24,
                'colors' => null,
                'stock' => 60,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => [],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Granulés de bois résineux — sac de 15 kg',
                'description' => "Le sac d'appoint : celui qu'on prend pour finir la semaine, ou pour essayer avant de commander une palette.\n\nGranulés de résineux pur, sans écorce ni liant — c'est ce qui donne peu de cendres et évite de vider le cendrier tous les deux jours. Certifiés DINplus et ENplus A1 : les deux références qui garantissent le taux d'humidité, le taux de cendres et le pouvoir calorifique, et que la plupart des fabricants de poêles exigent au titre de la garantie.\n\nSac de 15 kg. Granulés 6 mm, résineux, humidité inférieure à 10 %, taux de cendres inférieur à 0,7 %, environ 4,8 kWh/kg. Certification DINplus / ENplus A1.",
                'price' => 7,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 200,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => [],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Granulés de bois — palette de 66 sacs (990 kg)',
                'description' => "La commande d'une saison de chauffe pour un poêle, à peu près une tonne. C'est le format qui fait vraiment baisser le prix au kilo, et qui évite de repasser commande en janvier, au moment précis où tout le monde le fait et où les délais s'allongent.\n\nMêmes granulés certifiés que le sac à l'unité. Livrés filmés sur palette, à stocker au sec : un granulé qui prend l'humidité gonfle et bloque la vis sans fin du poêle.\n\nPalette de 66 sacs de 15 kg, soit 990 kg. Granulés 6 mm, résineux, humidité inférieure à 10 %, cendres inférieures à 0,7 %. Certification DINplus / ENplus A1. Livraison sur rendez-vous par camion à hayon, dépose au pied de la propriété sur sol stabilisé.",
                'price' => 399,
                'compare_at_price' => 449,
                'colors' => null,
                'stock' => 25,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => [],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Bûches densifiées jour & nuit — pack de 12',
                'description' => "Deux bûches compressées pour deux usages. Les claires, en résineux, montent vite en température : c'est la flambée du soir. Les sombres, en feuillus, brûlent lentement et tiennent la nuit — on en met une avant de se coucher et il reste des braises au matin.\n\nElles ne font pas de fumée noire et laissent très peu de cendres. Pratiques quand on n'a pas d'abri à bûches : un pack se range dans un placard.\n\nPack de 12 bûches (6 jour, 6 nuit), environ 10 kg. Sciure compressée sans liant ni colle, humidité inférieure à 8 %. Une bûche nuit tient environ 4 heures.",
                'price' => 24,
                'compare_at_price' => 29,
                'colors' => null,
                'stock' => 80,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => [],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Range-bûches Acier et Chêne',
                'description' => "Il tient l'équivalent de trois jours de feu à portée de main, ce qui évite la sortie sous la pluie au moment où le feu baisse. La structure en acier noir est ouverte sur les côtés : le bois continue de sécher à l'air de la pièce au lieu de suer contre une paroi.\n\nLa poignée supérieure en chêne massif sert vraiment : le range-bûches se déplace plein, d'une seule main.\n\nDimensions : 50 x 35 x 65 cm. Acier laqué noir, poignée chêne massif. Contenance environ 25 kg de bûches de 33 cm.",
                'price' => 240,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 14,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => [],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Serviteur de cheminée 4 pièces',
                'description' => "Pique-feu, pelle, balayette et pince, sur un pied qui les tient droits au lieu de les laisser glisser le long du mur. Les manches sont en chêne massif : ils ne chauffent pas comme le métal quand on les laisse trop près du foyer.\n\nAssez lourd pour qu'on décroche un outil sans que l'ensemble bascule — le défaut des serviteurs bon marché.\n\nDimensions : 20 x 20 x 68 cm. Acier laqué noir, manches chêne massif. Quatre outils inclus.",
                'price' => 130,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 16,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => [],
            ],
        ];

        $seeded = [];

        foreach ($products as $data) {
            $images = $data['images'];
            unset($data['images']);

            $slug = Str::slug($data['name']);
            $seeded[] = $slug;

            $product = Product::query()->updateOrCreate(
                ['slug' => $slug],
                $data + ['slug' => $slug, 'is_active' => true]
            );

            $product->images()->delete();

            foreach ($images as $position => $file) {
                $path = 'products/'.$file;

                if (! Storage::disk('public')->exists($path)) {
                    Storage::disk('public')->put(
                        $path,
                        file_get_contents(__DIR__.'/assets/products/'.$file)
                    );
                }

                ProductImage::create([
                    'product_id' => $product->id,
                    'path' => $path,
                    'position' => $position,
                ]);
            }
        }

        // Products from an earlier version of this catalogue would otherwise survive re-seeding
        // and show up in the shop alongside the current selection. Order history is unaffected:
        // order_items snapshots product_name and unit_price, and its product_id is nullOnDelete.
        Product::query()
            ->whereNotIn('slug', $seeded)
            ->each(function (Product $product) {
                $product->images()->delete();
                $product->delete();
            });
    }
}
