<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * The shop's catalogue.
 *
 * Every range is resold from the same supplier (guerrini-biomasse.com): names, prices and
 * photography come from their feed, so what a customer sees on a product card is the machine
 * that will be delivered. The photo files live in seeders/assets/products as
 * gb-<supplier id>.<ext> — named by supplier id rather than by slug because model names repeat
 * across manufacturers and several products share a filename on the supplier's side.
 *
 * Each product carries its whole gallery rather than a single shot: the first photograph keeps
 * the bare gb-<id>.<ext> name and is the one used on cards and in the blog covers, and the rest
 * are numbered gb-<id>-2, -3 and so on, in the supplier's own order. Most machines have four to
 * six — a broyeur photographed from behind tells a buyer more about the attelage than any
 * description does.
 *
 * Prices are the supplier's selling price; compare_at_price is their list price, and is left
 * null where they are not discounting rather than invented to manufacture a saving.
 *
 * Descriptions are ours, not the supplier's: they open on what the machine is actually like to
 * work with and who it suits, then give the specifics a buyer needs before ordering — power,
 * working width, the tractor it wants behind it, what arrives on the pallet. Where the supplier's
 * own copy was a spec dump or a broken HTML fragment, only the figures were kept.
 */
class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $elagage = Category::where('slug', 'tronconneuses-elagage')->firstOrFail();
        $autoportees = Category::where('slug', 'tracteurs-autoportees')->firstOrFail();
        $outils = Category::where('slug', 'outils-tracteur')->firstOrFail();
        $tondeuses = Category::where('slug', 'tondeuses-robots')->firstOrFail();
        $motoculture = Category::where('slug', 'motoculture')->firstOrFail();
        $bois = Category::where('slug', 'bois-chauffage')->firstOrFail();

        $products = [
            // ========================================================= TRONÇONNEUSES & ÉLAGAGE
            [
                'category_id' => $elagage->id,
                'name' => 'Élagueuse à batterie Campagnola T-Rex — 2 batteries',
                'description' => "Une élagueuse d'une seule main, tenue comme un sécateur, pour la taille que l'on fait en marchant dans le verger plutôt qu'en montant une échelle. Le bras ne fatigue pas parce que la machine ne pèse presque rien : on enchaîne les coupes une heure durant sans reposer l'outil, ce qui est exactement ce qu'on lui demande.\n\nRien à préparer avant de commencer. Pas de mélange, pas de lanceur, pas de chaîne à réaffûter au bout de dix coupes : on huile par le petit orifice à côté de la barre et on repart. Le silence change aussi la façon de travailler — on entend la branche craquer avant qu'elle ne tombe.\n\nGuide de 101,6 mm (4 pouces), chaîne à 8,5 m/s. Deux batteries 21,6 V fournies : 4 Ah pour environ 150 coupes, 2,5 Ah pour environ 90. Poids de la batterie 480 g. Livrée prête à l'emploi.",
                'price' => 205.06,
                'compare_at_price' => 256.32,
                'colors' => null,
                'stock' => 12,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-15132.jpg', 'gb-15132-2.jpg', 'gb-15132-3.jpg', 'gb-15132-4.jpg', 'gb-15132-5.jpg'],
            ],
            [
                'category_id' => $elagage->id,
                'name' => 'Greenworks GD40PSHK2 — Élagueuse et taille-haie sur perche 40V',
                'description' => "Deux outils sur un seul moteur : la tête d'élagage pour les branches hautes, la tête taille-haie articulée pour reprendre le dessus d'une haie sans monter dessus. On change d'accessoire en quelques secondes, et la rallonge de perche donne la hauteur qui évite l'escabeau.\n\nC'est la machine du terrain moyen, celui où l'on ne fait ni assez d'élagage ni assez de haie pour justifier deux appareils séparés. La batterie 40 V se partage avec le reste de la gamme, ce qui compte plus qu'il n'y paraît le jour où l'on en a une en charge et une sur l'outil.\n\nGuide d'élagage de 20 cm à lubrification automatique. Lames de taille-haie à double coupe alternée, tête articulée. Deux batteries 40 V / 2 Ah et chargeur inclus. Double interrupteur de sécurité contre les démarrages accidentels.",
                'price' => 225.09,
                'compare_at_price' => 281.36,
                'colors' => null,
                'stock' => 9,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-25967.png', 'gb-25967-2.jpg', 'gb-25967-3.jpg', 'gb-25967-4.jpg', 'gb-25967-5.jpg'],
            ],
            [
                'category_id' => $elagage->id,
                'name' => 'Blue Bird CS 22-04 & PS 23-25 Faster — Kit élagueuse et sécateur à batterie',
                'description' => "Le sécateur pour ce qui se coupe d'un geste, l'élagueuse pour ce qui ne passe pas : c'est la paire que l'on emporte réellement dans un verger, et elle arrive ici dans une mallette au lieu d'être achetée en deux fois.\n\nLes deux outils tiennent sous le kilo, batterie comprise. C'est la raison pour laquelle on finit la rangée : à ce poids-là, le poignet suit. Les lames du sécateur sont en acier suisse SK5 et coupent aussi bien le bois sec que le vert, avec deux ouvertures de coupe selon le diamètre.\n\nÉlagueuse CS 22-04 : guide de 100 mm, chaîne à 6 m/s, capacité de coupe 100 mm, 1 kg avec batterie. Sécateur PS 23-25 Faster : 0,9 kg, lame mobile interchangeable, écran de contrôle. Batteries 12,6 V / 2,5 Ah et mallette de transport incluses.",
                'price' => 238.22,
                'compare_at_price' => 297.77,
                'colors' => null,
                'stock' => 7,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-15236.png', 'gb-15236-2.jpg', 'gb-15236-3.jpg', 'gb-15236-4.jpg', 'gb-15236-5.jpg'],
            ],
            [
                'category_id' => $elagage->id,
                'name' => 'DeWalt DCMPS567P1-QW — Perche élagueuse à batterie 18V rallongeable',
                'description' => "Quatre mètres cinquante de portée, échelle comprise — sauf qu'il n'y a pas d'échelle. C'est tout l'argument de la perche rallongeable : on coupe les yeux levés, les deux pieds au sol, et on tourne autour de l'arbre au lieu de redescendre pour déplacer l'escabeau.\n\nÀ batterie plutôt qu'en thermique parce que le poids se porte à bout de bras : pas de moteur en haut de la perche, pas de mélange à préparer, pas de lanceur à tirer en équilibre. Le réservoir d'huile est semi-transparent, on voit le niveau sans dévisser le bouchon.\n\nGuide de 20 cm. Hauteur de coupe maximale 4,5 m. Batterie 18 V / 5 Ah et chargeur inclus. Lubrification de chaîne automatique.",
                'price' => 257.10,
                'compare_at_price' => 321.38,
                'colors' => null,
                'stock' => 8,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-15125.png', 'gb-15125-2.jpg', 'gb-15125-3.jpg', 'gb-15125-4.jpg', 'gb-15125-5.jpg'],
            ],
            [
                'category_id' => $elagage->id,
                'name' => 'Alpina AMT48Li kit — Perche multifonction élagueuse et taille-haie 48V',
                'description' => "La perche télescopique de 65 cm fait la différence entre atteindre la branche et y renoncer : 4 m avec la tête d'élagage, 4,3 m avec la tête taille-haie. La tête pivote sur 112°, ce qui permet de garder les bras bas pendant que l'outil, lui, travaille de travers.\n\nDétail que l'on n'apprécie qu'à l'usage : la tête d'élagage possède un support qui prend appui sur la branche. On relâche l'effort entre deux coupes au lieu de tenir la perche à bout de bras en continu.\n\nBarre de coupe de 25 cm, environ 80 coupes sur branches de 10 cm par charge. Batterie 48 V / 2 Ah incluse. Deux accessoires fournis : élagage et taille-haie.",
                'price' => 273.99,
                'compare_at_price' => 342.49,
                'colors' => null,
                'stock' => 6,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-24571.jpg', 'gb-24571-2.jpg', 'gb-24571-3.jpg', 'gb-24571-4.jpg', 'gb-24571-5.jpg'],
            ],
            [
                'category_id' => $elagage->id,
                'name' => 'Vesco X150AT — Élagueuse à batterie sur perche télescopique 160-250 cm',
                'description' => "Une perche de professionnel, pensée pour la journée entière et non pour la branche du dimanche. Le corps est en aluminium anodisé et la tête de coupe est affinée : on voit ce que l'on coupe, ce qui compte quand on travaille au-dessus de sa tête dans un verger dense.\n\nLa pompe de lubrification est électronique et non mécanique : l'huile arrive selon le besoin réel de la chaîne, et la coupe reste nette en fin de journée. La télescopie de 160 à 250 cm se règle en cours de travail, sans outil.\n\nMoteur brushless 700 W, 21,6 V. Guide de 6 pouces, chaîne 1/4 pouce à 36 maillons. Perche réglable de 160 à 250 cm. Attention : batterie et chargeur non inclus.",
                'price' => 314.40,
                'compare_at_price' => 393.00,
                'colors' => null,
                'stock' => 5,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-15202.png', 'gb-15202-2.jpg', 'gb-15202-3.jpg', 'gb-15202-4.jpg', 'gb-15202-5.jpg'],
            ],
            [
                'category_id' => $elagage->id,
                'name' => 'Campagnola Autolube M.3 Carving 8 pouces — Élagueuse pneumatique',
                'description' => "Une élagueuse à air comprimé : pas de batterie à recharger, pas de moteur à entretenir dans la tête, juste un tuyau et un compresseur au bout. Sur une exploitation qui a déjà l'air comprimé, c'est l'outil qui ne tombe jamais en panne de charge au milieu d'une rangée.\n\nLa chaîne tourne à 11 m/s, ce qui est très rapide pour du carving, et la barre étroite passe là où une tronçonneuse classique ne passe pas : c'est un outil de taille fine, pas d'abattage. Le réservoir de lubrification automatique évite d'y penser.\n\nPoids 1 800 g, châssis aluminium. Pression 10 bars, consommation 430 l/min. Guide 8 pouces (20 cm), chaîne 1/4 pouce, vitesse 11 m/s. Diamètre de branche maximal 180 mm. Utilisable à main levée ou sur perche fixe ou télescopique (accessoires non inclus). Fabriquée en Italie.",
                'price' => 337.04,
                'compare_at_price' => 421.30,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-15226.jpg', 'gb-15226-2.jpg', 'gb-15226-3.jpg', 'gb-15226-4.jpg', 'gb-15226-5.jpg'],
            ],
            [
                'category_id' => $elagage->id,
                'name' => 'Campagnola Laser 8 pouces — Élagueuse pneumatique châssis magnésium',
                'description' => "Montée sur perche, elle atteint cinq mètres sans échelle ; à main levée, elle se tient comme une vraie tronçonneuse — la poignée a été dessinée pour cela. C'est le modèle au-dessus de la M.3 : même principe pneumatique, châssis en alliage de magnésium.\n\nLe magnésium n'est pas là pour le catalogue. Il tient l'ensemble à 2,5 kg tout en résistant mieux, et surtout il ne givre pas comme le fait un corps qui condense — on taille en février, c'est un vrai sujet.\n\nPoids 2,5 kg, châssis magnésium et aluminium. Consommation d'air 400 l/min. Guide 8 pouces carving (20 cm), chaîne 1/4 pouce, vitesse 11 m/s. Diamètre de branche maximal 180 mm. Fabriquée en Italie, conforme à la directive 98/37/CE.",
                'price' => 404.80,
                'compare_at_price' => 506.00,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-15219.jpg', 'gb-15219-2.jpg', 'gb-15219-3.jpg', 'gb-15219-4.jpg', 'gb-15219-5.jpg'],
            ],
            [
                'category_id' => $elagage->id,
                'name' => 'Makita DUA301Z — Perche élagueuse à batterie 36V télescopique 3,80 m',
                'description' => "La perche coulisse de 2,60 m à 3,80 m pendant que l'on travaille : on ajuste à la branche au lieu de se déplacer. Guide de 30 cm et chaîne à 20 m/s — c'est nettement au-dessus des perches d'amateur, et cela se sent sur du bois de verger un peu dur.\n\nLa protection XPT contre la poussière et l'eau est ce qui la distingue vraiment : elle est faite pour être sortie par temps humide et rangée sale, pas pour être ménagée.\n\nMoteur 36 V (18 + 18). Guide de 300 mm, vitesse de chaîne 20 m/s. Perche télescopique 260-380 cm. Réservoir d'huile de 0,16 L à niveau visible. Attention : batterie et chargeur non inclus.",
                'price' => 427.32,
                'compare_at_price' => 534.15,
                'colors' => null,
                'stock' => 6,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-15104.png', 'gb-15104-2.jpg', 'gb-15104-3.jpg', 'gb-15104-4.jpg', 'gb-15104-5.jpg'],
            ],
            [
                'category_id' => $elagage->id,
                'name' => 'Husqvarna 592 XP — Tronçonneuse thermique professionnelle 5,6 kW',
                'description' => "La vraie tronçonneuse du rayon, celle qui abat et qui fait le bois de chauffage. 5 600 W pour 7,4 kg : c'est le rapport que cherchent les professionnels de la forêt, assez de couple pour ne pas caler dans un tronc de chêne, assez peu de poids pour la tenir une matinée.\n\nElle n'est pas destinée à la branche occasionnelle du jardin — pour cela, les élagueuses à batterie de ce rayon sont plus raisonnables et bien moins fatigantes. Elle est faite pour l'abattage, la découpe de grumes et les stères que l'on prépare soi-même.\n\nMoteur 2 temps, puissance 5 600 W. Poids 7,4 kg. Gamme professionnelle forestière Husqvarna. Équipement de protection individuelle vivement recommandé, non inclus.",
                'price' => 1159.00,
                'compare_at_price' => 1477.52,
                'colors' => null,
                'stock' => 3,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-30456.jpg'],
            ],

            // ================================================ TRACTEURS TONDEUSES & AUTOPORTÉES
            [
                'category_id' => $autoportees->id,
                'name' => 'GeoTech RM 75-610 BSM — Mini-rider 224 cm³ boîte mécanique',
                'description' => "L'autoportée la plus petite du rayon, et c'est précisément son intérêt : elle passe entre les massifs et contourne les arbres sans manœuvre, là où une machine à plateau large oblige à finir à la débroussailleuse. Pour un jardin encombré, un mini-rider tond plus vite qu'une grande autoportée.\n\nOn s'assoit dessus et on conduit, sans apprentissage. L'embrayage de lame est électromagnétique : la lame s'engage par un bouton, pas par un levier à forcer.\n\nMoteur Loncin OHV 224 cm³, 7,5 CV. Lame unique, largeur de coupe 61 cm. Ramassage. Boîte de vitesses mécanique. Conçue pour des surfaces résidentielles petites à moyennes.",
                'price' => 906.13,
                'compare_at_price' => 1132.66,
                'colors' => null,
                'stock' => 5,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-28677.png', 'gb-28677-2.jpg', 'gb-28677-3.jpg', 'gb-28677-4.jpg', 'gb-28677-5.jpg'],
            ],
            [
                'category_id' => $autoportees->id,
                'name' => 'GeoTech-Pro GT-MR 76 — Tracteur tondeuse 432 cm³ coupe 76 cm',
                'description' => "Le palier au-dessus du mini-rider : 76 cm de coupe au lieu de 61, et un moteur qui passe de 224 à 432 cm³. Concrètement, cela retire un passage sur deux et cela ne bronche pas dans l'herbe qui a pris dix jours de pluie.\n\nLa boîte mécanique à cinq rapports plus marche arrière demande de changer de vitesse, contrairement à une hydrostatique — en échange elle est plus simple, moins chère et se répare partout.\n\nMoteur essence Loncin 1P90F-1, 432 cm³. Largeur de coupe 76 cm. Transmission mécanique, 5 vitesses avant et 1 arrière. Hauteur de coupe réglable sur 6 positions.",
                'price' => 1419.41,
                'compare_at_price' => 1774.26,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-28534.png', 'gb-28534-2.jpg', 'gb-28534-3.jpg', 'gb-28534-4.jpg', 'gb-28534-5.jpg'],
            ],
            [
                'category_id' => $autoportees->id,
                'name' => 'Alpina AT3 98 HA — Tracteur tondeuse coupe 98 cm éjection latérale',
                'description' => "Faite pour l'herbe haute et le terrain qu'on ne tond pas toutes les semaines. L'éjection latérale ne bourre pas comme un bac se remplit : dans une friche de fin de printemps, c'est ce qui permet d'avancer sans s'arrêter toutes les trois minutes pour vider.\n\nDeux lames en acier sur un plateau de 98 cm, engagées électromagnétiquement. Sept hauteurs de coupe de 25 à 80 mm au levier — les 80 mm servent vraiment quand on reprend un terrain laissé un mois.\n\nMoteur Stiga ST 400, 414 cm³. Largeur de coupe 98 cm, deux lames. Éjection latérale avec déflecteur de série. 7 hauteurs de coupe de 25 à 80 mm. Surface conseillée jusqu'à 5 000 m².",
                'price' => 1670.65,
                'compare_at_price' => 2088.31,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-28513.png', 'gb-28513-2.jpg', 'gb-28513-3.jpg', 'gb-28513-4.jpg', 'gb-28513-5.jpg'],
            ],
            [
                'category_id' => $autoportees->id,
                'name' => 'GeoTech-Pro PRTM 180-1020 CM — Tracteur tondeuse 17 CV bac 280 L',
                'description' => "Un bac de 280 litres, c'est le nombre qui compte sur cette machine : il espace les vidages, et le vidage est le vrai temps perdu d'une tonte avec ramassage. Sur un terrain d'un demi-hectare, la différence avec un bac de 200 L se compte en dizaines de minutes.\n\nDix-sept chevaux et une boîte mécanique à cinq rapports : on choisit son allure selon l'herbe plutôt que de subir une vitesse unique. Deux modes de coupe, ramassage ou éjection, selon la saison.\n\nMoteur essence Loncin LC1P92F-1, 17 CV nominaux. Bac de ramassage 280 L. Transmission mécanique, 5 vitesses avant, point mort et marche arrière. Conçue pour terrains moyens à grands.",
                'price' => 1814.47,
                'compare_at_price' => 2268.09,
                'colors' => null,
                'stock' => 3,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-28527.png', 'gb-28527-2.jpg', 'gb-28527-3.jpg', 'gb-28527-4.jpg', 'gb-28527-5.jpg'],
            ],
            [
                'category_id' => $autoportees->id,
                'name' => 'GeoTech-Pro PRTM 200-1020 H-CM — Autoportée hydrostatique 20 CV coupe 102 cm',
                'description' => "L'hydrostatique est ce que l'on remarque en premier : plus de rapport à passer, on accélère et on ralentit à la pédale, y compris en marche arrière au milieu d'une manœuvre. Autour des massifs et des arbres, cela change complètement la conduite.\n\nDerrière, un bicylindre de 586 cm³ et un plateau à double lame de 102 cm : elle a de la réserve dans les pentes et dans l'herbe grasse, là où un monocylindre commence à peiner. Carrosserie en acier peint, construction semi-professionnelle.\n\nMoteur Loncin bicylindre 586 cm³, 20 CV nominaux. Transmission hydrostatique. Plateau double lame, largeur de coupe 102 cm. Bac de ramassage. Pour surfaces herbeuses moyennes à grandes.",
                'price' => 2162.38,
                'compare_at_price' => 2702.97,
                'colors' => null,
                'stock' => 3,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-28485.png', 'gb-28485-2.jpg', 'gb-28485-3.jpg', 'gb-28485-4.jpg', 'gb-28485-5.jpg'],
            ],
            [
                'category_id' => $autoportees->id,
                'name' => 'Roques et Lecoeur RL998K — Autoportée hydrostatique 18 CV bac 240 L',
                'description' => "Elle arrive avec le kit mulching et le crochet d'attelage déjà fournis, ce qui est rare à ce prix et évite deux achats séparés. Le mulching sert l'été, quand l'herbe est courte et qu'on ne veut plus vider de bac ; l'attelage sert le reste de l'année, pour la remorque.\n\nTransmission hydrostatique et bicylindre de 18 CV : la conduite est souple et la machine ne s'essouffle pas sur 5 000 m². C'est une autoportée de propriétaire, pas de professionnel — mais complète.\n\nMoteur RL550 bicylindre, 18 CV. Transmission hydrostatique. Plateau de coupe 98 cm, bac de ramassage 240 L. Kit mulching et crochet d'attelage fournis. Jardins jusqu'à 5 000 m².",
                'price' => 2499.17,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 3,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-31198.jpg'],
            ],
            [
                'category_id' => $autoportees->id,
                'name' => 'Stihl RT 5097.1 — Tracteur de pelouse hydrostatique coupe 95 cm',
                'description' => "Les deux lames du plateau sont décalées de 90° et synchronisées : elles s'emboîtent au lieu de se croiser, ce qui donne une coupe régulière sur toute la largeur au lieu d'une bande moins nette au centre. C'est le détail d'ingénierie qui justifie l'écart de prix avec une autoportée d'entrée de gamme.\n\nBoîte hydrostatique, moteur maison Stihl, finition et confort de conduite au niveau de la marque. Un large catalogue d'accessoires vient s'y greffer si le terrain évolue.\n\nMoteur Stihl EVC 4000, 452 cm³, 8,2 kW. Transmission hydrostatique. Largeur de coupe 95 cm, plateau synchronisé deux lames. Bac de ramassage 250 L. Superficie conseillée jusqu'à 6 000 m².",
                'price' => 3340.83,
                'compare_at_price' => 3361.83,
                'colors' => null,
                'stock' => 2,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-31463.jpg', 'gb-31463-2.jpg', 'gb-31463-3.jpg', 'gb-31463-4.jpg'],
            ],
            [
                'category_id' => $autoportees->id,
                'name' => 'Snapper ERX96 — Autoportée à batterie 72V éjection latérale et mulching',
                'description' => "Une autoportée qui ne fait pas de bruit et ne sent pas l'essence : on tond tôt le dimanche sans fâcher personne, et on range la machine dans un garage attenant sans odeur de carburant. Pour beaucoup de propriétés, c'est l'argument décisif.\n\nÉjection latérale de série pour la tonte courante, et le bouchon mulching est fourni pour l'été. Pas de vidange, pas de bougie, pas de filtre à air : l'entretien d'une autoportée thermique disparaît presque entièrement.\n\nBatterie 72 V / 28 Ah. Éjection latérale, kit mulching inclus de série. Surface conseillée jusqu'à 5 000 m².",
                'price' => 4035.53,
                'compare_at_price' => 5044.41,
                'colors' => null,
                'stock' => 2,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-29006.png', 'gb-29006-2.jpg', 'gb-29006-3.jpg', 'gb-29006-4.jpg', 'gb-29006-5.jpg'],
            ],
            [
                'category_id' => $autoportees->id,
                'name' => 'Honda HF2625HME — Autoportée hydrostatique',
                'description' => "Honda vend ici du confort de conduite avant la performance brute : direction douce, transmission hydrostatique progressive, position de conduite soignée. Sur une propriété où la tonte prend deux heures chaque semaine, c'est ce qui fait la différence entre une corvée et un moment tranquille.\n\nLa robustesse est l'autre moitié de l'argument. Ces machines se revendent bien dix ans après, ce qui relativise le prix d'achat.\n\nAutoportée à transmission hydrostatique, moteur Honda de dernière génération. Ramassage. Finition et fiabilité de la gamme HF.",
                'price' => 4940.83,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 2,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => [
                    'gb-31226.jpg',
                    'gb-31226-2.jpg',
                    'gb-31226-3.jpg',
                    'gb-31226-4.jpg',
                    'gb-31226-5.jpg',
                    'gb-31226-6.jpg',
                ],
            ],
            [
                'category_id' => $autoportees->id,
                'name' => 'Castelgarden XHT 240 4WD — Autoportée 4 roues motrices bac 360 L',
                'description' => "Quatre roues motrices : la machine du terrain en pente et du sol qui reste humide, là où une autoportée à deux roues motrices patine et marque la pelouse. Avec un bac de 360 litres et un plateau de 102 cm à deux lames, c'est le haut du rayon, pour les très grandes surfaces.\n\nLes roues anti-scalping du carter évitent que le plateau ne morde la terre sur les bosses — sur un terrain irrégulier, c'est la différence entre une pelouse et des plaques pelées.\n\nMoteur Briggs & Stratton Intek 8240 V-Twin bicylindre, 724 cm³, lubrification forcée par pompe à huile. 4 roues motrices. Plateau 102 cm, deux lames, roues anti-scalping. Bac 360 L. Embrayage de lames électromagnétique électronique. Pente admissible jusqu'à 25 % — ne jamais travailler en travers de la pente, risque de retournement.",
                'price' => 7000.00,
                'compare_at_price' => null,
                'colors' => null,
                'stock' => 1,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-30459.jpg'],
            ],

            // ============================================================== OUTILS POUR TRACTEUR
            [
                'category_id' => $outils->id,
                'name' => 'BlackStone B-BF 1000 — Fourche à bottes attelage 3 points',
                'description' => "Trois pointes et rien d'autre : la pointe centrale de 85 cm traverse la botte, les deux latérales de 30 cm l'empêchent de tourner pendant le transport. C'est tout ce qu'il faut pour déplacer du foin, et c'est pour cela que l'outil dure — il n'y a rien qui puisse casser.\n\nÀ 35 kg, elle se manipule à deux pour l'attelage et ne demande aucune puissance hydraulique : elle se monte sur le relevage et travaille avec lui.\n\nAttelage 3 points. Pointe centrale 85 cm, pointes latérales 30 cm, écartement 50 cm, largeur 80 cm. Charge 500 kg. Poids 35 kg, châssis acier émaillé. Attaches inférieures Ø 22 et 28 mm, troisième point Ø 19 et 25 mm.",
                'price' => 206.98,
                'compare_at_price' => 258.72,
                'colors' => null,
                'stock' => 10,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-14794.png', 'gb-14794-2.jpg', 'gb-14794-3.jpg', 'gb-14794-4.jpg', 'gb-14794-5.jpg'],
            ],
            [
                'category_id' => $outils->id,
                'name' => 'GeoTech D1200 — Fourche à palettes arrière 1200 kg',
                'description' => "Une porte-palette qui se monte à l'arrière du tracteur plutôt qu'un chariot élévateur que l'on n'a pas. Pour rentrer une palette de granulés, décharger un livreur ou déplacer des big-bags, c'est l'outil qui rend une exploitation autonome.\n\nL'écartement des fourches se règle sur quatre positions, ce qui permet de prendre aussi bien une palette Europe qu'un bin de récolte. Les pointes se bloquent en position fermée pour le transport sur route, comme l'exige la réglementation.\n\nAttelage 3 points, porte-palette postérieure. Capacité 1 200 kg. Longueur des pointes environ 0,90 m, largeur 100 mm par fourche. Écartement réglable sur 4 positions, blocage des pointes pour le transport. Châssis acier émaillé, série lourde.",
                'price' => 500.22,
                'compare_at_price' => 625.28,
                'colors' => null,
                'stock' => 6,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-14752.jpg', 'gb-14752-2.jpg', 'gb-14752-3.jpg', 'gb-14752-4.jpg', 'gb-14752-5.jpg'],
            ],
            [
                'category_id' => $outils->id,
                'name' => 'Francini P 150 — Benne basculante 3 ridelles ouvrantes',
                'description' => "Les trois ridelles s'ouvrent et se retirent : on charge le fumier par le côté au lieu de le lancer par-dessus bord, et on décharge du bois en le faisant glisser plutôt qu'en le soulevant. C'est ce qui sépare une benne utilisable d'un simple caisson.\n\nLe levier de basculement se manœuvre depuis le sol, rapidement. Sur une propriété, cette benne remplace la remorque pour tout ce qui est court, sale et lourd : gravats, bûches, terre, déchets de taille.\n\nAttelage 3 points, caisson basculant. Ridelles latérales et arrière de 46 cm, ouvrantes et amovibles. Levier de basculement rapide. Construction robuste pour usage intensif.",
                'price' => 806.08,
                'compare_at_price' => 1007.60,
                'colors' => null,
                'stock' => 5,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-14659.png', 'gb-14659-2.jpg', 'gb-14659-3.jpg', 'gb-14659-4.jpg', 'gb-14659-5.jpg'],
            ],
            [
                'category_id' => $outils->id,
                'name' => 'BullMach Ermes 145 S — Broyeur porté série légère déport manuel',
                'description' => "Le premier vrai broyeur du rayon : 145 cm de largeur utile pour de l'herbe, des sarments et des petits arbustes. Série légère veut dire ce que cela dit — il n'est pas fait pour du taillis de trois ans, mais il avale sans broncher l'entretien courant d'un pré ou d'une vigne.\n\nLe déport latéral est manuel : on le règle à l'arrêt, une fois, selon que l'on longe une clôture à droite ou à gauche. Le rouleau arrière règle la hauteur de coupe et empêche le rotor de mordre la terre.\n\nAttelage 3 points, largeur de travail 145 cm, encombrement 163 cm. Poids 194 kg. Rotor à marteaux, transmission 3 courroies, rouleau stabilisateur arrière. Déport manuel : 83,4 cm à gauche, 110,4 cm à droite. Livré monté, huile à niveau, arbre à cardan inclus.",
                'price' => 943.94,
                'compare_at_price' => 1179.93,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-18375.png', 'gb-18375-2.jpg', 'gb-18375-3.jpg', 'gb-18375-4.jpg', 'gb-18375-5.jpg'],
            ],
            [
                'category_id' => $outils->id,
                'name' => 'BlackStone BV 100 L — Broyeur d\'accotement à bras série légère',
                'description' => "Un broyeur à bras déporté, c'est la réponse au fossé et au talus : le tracteur reste sur le plat, l'outil descend ou monte à côté de lui. Le mouvement est entièrement hydraulique, horizontal et vertical, ce qui permet aussi de reprendre le dessus d'une haie.\n\nEn série légère, il reste destiné à l'herbe, aux sarments et aux petits arbustes — pas au bois. C'est le bon compromis pour un particulier avec un long linéaire de fossés ou de bords de chemin.\n\nAttelage 3 points, bras déporté à mouvement hydraulique horizontal et vertical. Série légère. Usages : coupe d'herbe, broyage de tiges et de sarments, taille de haies, fossés, talus et pentes.",
                'price' => 1204.30,
                'compare_at_price' => 1505.38,
                'colors' => null,
                'stock' => 3,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-18312.png', 'gb-18312-2.jpg', 'gb-18312-3.jpg', 'gb-18312-4.jpg', 'gb-18312-5.jpg'],
            ],
            [
                'category_id' => $outils->id,
                'name' => 'Premium Line Fu Top 96 M — Broyeur porté 93 cm pour petits tracteurs',
                'description' => "Le broyeur des petits tracteurs, et il faut le prendre au sérieux : 110 kg seulement, conseillé de 10 à 20 CV. Beaucoup de propriétaires achètent un broyeur trop lourd pour leur machine et se retrouvent avec un outil qui déséquilibre l'ensemble et que le relevage peine à porter. Celui-ci est dimensionné pour un micro-tracteur.\n\nLe déport manuel se règle sur cinq positions, ce qui suffit pour longer un mur ou une clôture. Le rouleau arrière est réglable en hauteur.\n\nAttelage 3 points 1ʳᵉ catégorie. Largeur de travail 93 cm, encombrement avec patins 115 cm. Poids 110 kg. Rotor à marteaux, transmission 2 courroies, mécanisme à quadrilatère. Déport manuel 5 positions. Conseillé pour tracteurs de 10 à 20 CV. Livré prêt à l'emploi, arbre à cardan inclus.",
                'price' => 1427.94,
                'compare_at_price' => 1784.93,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-17899.jpg', 'gb-17899-2.jpg', 'gb-17899-3.jpg', 'gb-17899-4.jpg'],
            ],
            [
                'category_id' => $outils->id,
                'name' => 'Top Line MF 130 — Broyeur porté série médium 130 cm',
                'description' => "La série médium est celle qui accepte de tout : herbe, bois de taille, paille, sous-bois. Le rotor est à marteaux dentés avec contre-lame et tiges de ramassage, autrement dit il ramasse ce qui est couché au sol au lieu de passer dessus — c'est ce que l'on cherche dans une vigne ou un verger après la taille.\n\nLes roulements à rotule montés avec double bague d'étanchéité et le boîtier Comer sont les organes qui décident de la durée de vie d'un broyeur. Ici ils sont dimensionnés pour durer.\n\nLargeur de travail 130 cm, encombrement avec patins 143 cm. Poids 268 kg. Puissance absorbée 25 CV, tracteur requis de 30 à 45 CV. Attelage fixe, transmission 3 courroies, boîte Comer à arbre lubrifié. Marteaux dentés, contre-lame, tiges de ramassage, coffre arrière ouvrant, rouleau stabilisateur.",
                'price' => 2060.21,
                'compare_at_price' => 2575.26,
                'colors' => null,
                'stock' => 3,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-17885.jpg', 'gb-17885-2.jpg', 'gb-17885-3.jpg', 'gb-17885-4.jpg', 'gb-17885-5.jpg'],
            ],
            [
                'category_id' => $outils->id,
                'name' => 'Top Line MS 160 — Broyeur porté série médium déport hydraulique',
                'description' => "Le déport hydraulique est ce qui sépare cet outil du MF 130 : on décale le broyeur depuis le siège, en travaillant, pour longer un rang de vigne ou un pied de clôture sans descendre du tracteur. Sur un chantier avec beaucoup de bordures, on gagne une heure par hectare.\n\nMême série médium, même polyvalence — herbe, sarments, résidus de taille — avec 160 cm de largeur au lieu de 130, donc moins de passages sur les surfaces ouvertes.\n\nSérie médium, largeur de travail 160 cm. Déport latéral hydraulique commandé depuis le tracteur. Rotor à marteaux, rouleau stabilisateur arrière. Attelage 3 points.",
                'price' => 2553.49,
                'compare_at_price' => 3191.86,
                'colors' => null,
                'stock' => 2,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-17710.jpg', 'gb-17710-2.jpg', 'gb-17710-3.jpg', 'gb-17710-4.jpg', 'gb-17710-5.jpg'],
            ],
            [
                'category_id' => $outils->id,
                'name' => 'Ceccato Trincione 400 4T1800ID — Broyeur porté série lourde déport hydraulique',
                'description' => "Série lourde : 495 kg de châssis conçu pour encaisser les chocs pendant des années, et non pour passer une saison. À 180 cm de largeur utile et 50 à 80 CV de tracteur demandés, on est sur du matériel d'exploitation, pas de propriété.\n\nQuatre courroies de transmission au lieu de trois, et un regard de contrôle du niveau d'huile sur l'arbre entre la poulie et le réducteur : on vérifie sans démonter, donc on vérifie vraiment.\n\nLargeur de travail 180 cm, encombrement avec patins 199 cm. Poids 495 kg. Tracteur conseillé de 50 à 80 CV. Déport hydraulique. Transmission 4 courroies, regard de contrôle d'huile. Travaux : herbe, taille, paille et résidus. Fabriqué en Italie.",
                'price' => 3303.34,
                'compare_at_price' => 4129.18,
                'colors' => null,
                'stock' => 2,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-17511.jpg', 'gb-17511-2.jpg', 'gb-17511-3.jpg', 'gb-17511-4.jpg', 'gb-17511-5.jpg'],
            ],
            [
                'category_id' => $outils->id,
                'name' => 'Top Line A-PS 200 — Broyeur d\'accotement à bras série lourde',
                'description' => "Le haut du rayon : un broyeur d'accotement à bras entièrement hydraulique, horizontal et vertical, capable de nettoyer un bord de route puis de se redresser pour broyer une haie. C'est l'outil des collectivités et des grandes exploitations à long linéaire.\n\nDeux vérins commandent le déport latéral, et le rotor est équilibré dynamiquement — sur un bras déporté, un rotor mal équilibré détruit ses paliers en une saison. Fabrication italienne intégrale.\n\nSérie lourde, bras à mouvement hydraulique horizontal et vertical. Déport latéral par 2 vérins hydrauliques. Transmission latérale 3 courroies. Rotor à équilibrage dynamique. Usages : bords de route, accotements, fossés, haies et buissons, terrains inclinés. Fabriqué en Italie.",
                'price' => 5015.55,
                'compare_at_price' => 6269.44,
                'colors' => null,
                'stock' => 1,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-17546.jpg', 'gb-17546-2.jpg', 'gb-17546-3.jpg', 'gb-17546-4.jpg', 'gb-17546-5.jpg'],
            ],

            // =============================================================== TONDEUSES & ROBOTS
            [
                'category_id' => $tondeuses->id,
                'name' => 'Black & Decker BCMW33184L2-QW — Tondeuse à batterie 36V + batterie 18V offerte',
                'description' => "La tondeuse du petit jardin de ville : légère, sans câble à contourner et sans moteur thermique à réveiller le samedi matin. On la sort, on appuie, on tond — les commandes tiennent en deux gestes.\n\nDeux batteries 18 V se combinent pour donner les 36 V, et elles sont compatibles avec le reste de la gamme de la marque : la perceuse et le taille-haie puisent dans le même stock. C'est ce qui rend l'investissement raisonnable.\n\nDeux batteries 18 V / 4,04 Ah et chargeur inclus, plus une batterie 18 V / 2 Ah offerte. Surface conseillée jusqu'à 500 m². Poids contenu, commandes simplifiées.",
                'price' => 207.92,
                'compare_at_price' => 259.90,
                'colors' => null,
                'stock' => 14,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-26803.png', 'gb-26803-2.jpg', 'gb-26803-3.jpg', 'gb-26803-4.jpg', 'gb-26803-5.jpg'],
            ],
            [
                'category_id' => $tondeuses->id,
                'name' => 'GeoTech Pro S51-200 BMSGW — Tondeuse thermique tractée coupe 51 cm',
                'description' => "Quatre modes de coupe sur une seule machine : ramassage, mulching, éjection arrière et éjection latérale. Peu de tondeuses de ce prix font les quatre, et c'est ce qui permet de suivre la saison — bac au printemps quand l'herbe pousse vite, mulching l'été quand elle sèche, éjection quand on a laissé passer quinze jours.\n\nLa traction arrière fait le reste : sur 51 cm de coupe et un terrain en pente, on guide la machine au lieu de la pousser. Le guidon se rabat pour le rangement.\n\nMoteur GeoTech 196 cm³. Largeur de coupe 51 cm. Traction arrière. Bac de ramassage 65 L, mulching, éjection arrière et latérale. Guidon rabattable avec poignée de réglage d'inclinaison.",
                'price' => 265.60,
                'compare_at_price' => 332.00,
                'colors' => null,
                'stock' => 11,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-26649.jpg', 'gb-26649-2.jpg', 'gb-26649-3.jpg', 'gb-26649-4.jpg', 'gb-26649-5.jpg'],
            ],
            [
                'category_id' => $tondeuses->id,
                'name' => 'Greenworks GD48LM46SP — Tondeuse tractée à batterie 48V coupe 46 cm',
                'description' => "Tractée et à vitesse variable : on règle l'allure de la machine à son propre pas plutôt que l'inverse, ce qui compte sur un terrain de plusieurs centaines de mètres carrés. Le moteur brushless ne demande aucun entretien et vibre peu.\n\nTrois configurations — éjection arrière, éjection latérale, obturateur mulching — et un châssis en acier, pas en plastique : elle encaisse les chocs de bordure qui fendent les carters bon marché.\n\nBatterie 48 V, moteur brushless à vitesse variable. Largeur de coupe 46 cm. Tondeuse 3 en 1 : éjection arrière, éjection latérale, mulching. Châssis acier, guidon pliant à décrochage rapide, réglage de hauteur par bouton. Attention : batterie et chargeur non inclus.",
                'price' => 319.91,
                'compare_at_price' => 399.89,
                'colors' => null,
                'stock' => 9,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-27306.png', 'gb-27306-2.jpg', 'gb-27306-3.jpg', 'gb-27306-4.jpg', 'gb-27306-5.jpg'],
            ],
            [
                'category_id' => $tondeuses->id,
                'name' => 'Worx Landroid WR147E.1 — Robot tondeuse 1000 m² avec fil périphérique',
                'description' => "Le robot d'entrée de gamme qui fait le travail : on pose le fil périphérique un après-midi, et l'on ne retouche plus à la pelouse de la saison. Il gère les petits dénivelés et les passages étroits, ce qui est le vrai test d'un jardin réel avec ses recoins.\n\nIl coupe en mulching, donc l'herbe hachée retourne au sol et nourrit la pelouse : pas de bac à vider, pas de déchets verts à sortir. Une fonction de coupe de bordure limite la reprise à la débroussailleuse.\n\nSurface conseillée jusqu'à 1 000 m². Batterie 20 V / 4 Ah, compatible gamme Worx PowerShare. Moteur brushless. Coupe mulching, fonction bordure. Installation par fil périphérique, sans assistance. Capteurs d'obstacles offerts.",
                'price' => 399.92,
                'compare_at_price' => 499.90,
                'colors' => null,
                'stock' => 8,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-25422.png', 'gb-25422-2.png', 'gb-25422-3.jpg', 'gb-25422-4.jpg', 'gb-25422-5.jpg'],
            ],
            [
                'category_id' => $tondeuses->id,
                'name' => 'Stiga G 300 — Robot tondeuse petite surface batterie E-Power',
                'description' => "Pour un jardin de ville où la tonte est une contrainte disproportionnée par rapport à la surface. Le G 300 hache finement et laisse l'herbe au sol : la pelouse se nourrit d'elle-même et il n'y a jamais rien à sortir.\n\nQuarante minutes de charge pour deux heures et demie de tonte, ce qui autorise deux passages par jour — c'est le rythme recommandé, et c'est aussi ce qui donne une pelouse toujours nette plutôt qu'une coupe hebdomadaire visible.\n\nBatterie E-Power 2 Ah, station de charge incluse. 40 minutes de charge pour 2 h 30 d'autonomie. Coupe mulching. Capot externe amovible et lavable. Programmation simple.",
                'price' => 497.99,
                'compare_at_price' => 622.49,
                'colors' => null,
                'stock' => 7,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-25373.png', 'gb-25373-2.jpg', 'gb-25373-3.jpg', 'gb-25373-4.jpg', 'gb-25373-5.jpg'],
            ],
            [
                'category_id' => $tondeuses->id,
                'name' => 'Ambrogio L32 Deluxe — Robot tondeuse avec fil périphérique 25,9V',
                'description' => "Un robot italien de facture soignée, dans la catégorie des petits jardins. Soixante minutes de tonte pour soixante minutes de charge : il travaille par cycles courts et réguliers, ce qui suffit largement sur la surface pour laquelle il est prévu.\n\nLe fil périphérique reste la méthode la plus fiable pour délimiter un jardin compliqué — massifs, terrasse, potager. Une fois posé, il ne bouge plus.\n\nBatterie lithium 25,9 V / 2,5 Ah. Autonomie de coupe 60 minutes, temps de charge 60 minutes. Installation par fil périphérique.",
                'price' => 633.40,
                'compare_at_price' => 791.75,
                'colors' => null,
                'stock' => 6,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-25785.png', 'gb-25785-2.jpg', 'gb-25785-3.jpg', 'gb-25785-4.jpg', 'gb-25785-5.jpg'],
            ],
            [
                'category_id' => $tondeuses->id,
                'name' => 'Marina Systems Agri 57 SKW 3V ZHW — Tondeuse thermique tractée moteur Kawasaki',
                'description' => "Une tondeuse à pousser de qualité agricole : carrosserie en acier émaillé, pare-chocs avant en fer, moteur Kawasaki FJ180. Elle est faite pour les grands jardins et les abords de ferme, là où l'herbe est dense et où le terrain cache des pierres.\n\nLa boîte à trois rapports est ce qui la distingue d'une tondeuse tractée ordinaire : on ralentit dans l'herbe grasse et on accélère sur le rase, au lieu de subir une vitesse unique et de bourrer.\n\nMoteur Kawasaki FJ180. Largeur de coupe 57 cm. Traction mécanique arrière, boîte à 3 rapports. Carrosserie acier émaillé, pare-chocs avant métallique. Surface conseillée jusqu'à 2 900 m².",
                'price' => 748.93,
                'compare_at_price' => 936.16,
                'colors' => null,
                'stock' => 5,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-27264.png', 'gb-27264-2.jpg', 'gb-27264-3.jpg', 'gb-27264-4.jpg', 'gb-27264-5.jpg'],
            ],
            [
                'category_id' => $tondeuses->id,
                'name' => 'MOVA 600 KIT — Robot tondeuse sans fil périphérique + 81 lames',
                'description' => "Pas de fil à enterrer, pas d'antenne RTK à planter : il cartographie le jardin tout seul, à la caméra et au LiDAR. On le sort de sa boîte et il travaille le jour même — c'est ce qui a changé sur cette génération de robots.\n\nLe LiDAR 3D détecte en temps réel le mobilier de jardin, les arbres et les petits animaux, et il corrige sa trajectoire au lieu de buter. Le kit de 81 lames de rechange couvre plusieurs saisons.\n\nNavigation UltraView sans fil périmétrique ni station RTK. Capteur LiDAR 3D avec détection d'obstacles en temps réel. Kit de 81 lames de rechange inclus. Usage domestique.",
                'price' => 879.20,
                'compare_at_price' => 1099.00,
                'colors' => null,
                'stock' => 5,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-25729.png', 'gb-25729-2.jpg', 'gb-25729-3.jpg', 'gb-25729-4.jpg', 'gb-25729-5.jpg'],
            ],
            [
                'category_id' => $tondeuses->id,
                'name' => 'Dreame A2 2000 — Robot tondeuse 2000 m² sans installation',
                'description' => "Deux mille mètres carrés gérés sans un mètre de fil. La navigation combine un LiDAR 3D et une caméra IA, et le système EdgeMaster déporte le disque vers le bord : la finition de bordure se fait toute seule, ce qui est précisément la limite des robots de génération précédente.\n\nLa 4G est incluse avec trois ans de forfait : on surveille et on reprogramme depuis n'importe où, sans dépendre de la portée du wifi au fond du jardin.\n\nSurface jusqu'à 2 000 m². Navigation OmniSense 2.0 : LiDAR 3D et caméra IA HDR 1080p. Coupe de bordure EdgeMaster. Application Dreamehome : planification, zones personnalisées, suivi en temps réel. Connectivité 4G avec forfait de données inclus 3 ans.",
                'price' => 1279.20,
                'compare_at_price' => 1599.00,
                'colors' => null,
                'stock' => 4,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-25694.png', 'gb-25694-2.jpg', 'gb-25694-3.jpg', 'gb-25694-4.jpg', 'gb-25694-5.jpg'],
            ],
            [
                'category_id' => $tondeuses->id,
                'name' => 'Stiga Vista A 140v — Robot tondeuse 14 000 m² batterie 14 Ah',
                'description' => "Quatorze mille mètres carrés et des pentes jusqu'à 50 % : ce robot remplace une autoportée sur une grande propriété, un parc arboré ou un site d'entreprise. Il gère jusqu'à trente zones de tonte distinctes, y compris des parcelles éloignées les unes des autres.\n\nÀ ce niveau, l'absence de fil périphérique n'est plus un confort mais une nécessité : personne ne pose et n'entretient deux kilomètres de fil. La batterie de 14 Ah lui donne l'autonomie qui va avec la surface.\n\nSurface jusqu'à 14 000 m². Sans fil périphérique. Batterie E-Power 14 Ah. Jusqu'à 30 zones de tonte gérées. Pentes admissibles jusqu'à 50 %.",
                'price' => 5039.28,
                'compare_at_price' => 6299.10,
                'colors' => null,
                'stock' => 1,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-25652.png', 'gb-25652-2.jpg', 'gb-25652-3.jpg', 'gb-25652-4.jpg', 'gb-25652-5.jpg'],
            ],

            // ================================================ DÉBROUSSAILLEUSES & MOTOCULTURE
            [
                'category_id' => $motoculture->id,
                'name' => 'Ryobi RBC18X20B4F — Débroussailleuse à batterie 18V 4 Ah',
                'description' => "La débroussailleuse que l'on attrape pour vingt minutes de finition : bordures, pied de mur, tour des arbres. À 4,7 kg sans batterie et bien équilibrée, on la tient d'une main le temps de faire un contour, ce qui est impossible avec une thermique.\n\nDeux vitesses au choix : la lente économise la batterie sur l'herbe tendre, la rapide sert quand ça résiste. La tête Tap & Go se recharge en fil d'une pression au sol, sans démontage.\n\nBatterie 18 V / 4 Ah, compatible avec toute la gamme Ryobi ONE+. Diamètre de coupe 20-30 cm. Poids 4,7 kg sans batterie ni accessoires. Tête monofil Tap & Go. Guidon et poignée revêtus de caoutchouc souple.",
                'price' => 201.74,
                'compare_at_price' => 252.17,
                'colors' => null,
                'stock' => 15,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-21352.png', 'gb-21352-2.jpg', 'gb-21352-3.jpg', 'gb-21352-4.jpg', 'gb-21352-5.jpg'],
            ],
            [
                'category_id' => $motoculture->id,
                'name' => 'Eurosystems La Zappa — Motobineuse essence 4 CV moteur Loncin',
                'description' => "La petite motobineuse du potager : assez légère pour être portée jusqu'au carré de légumes, assez costaude pour retourner la terre avant les semis. Elle travaille les sols souples sur une trentaine de mètres carrés — c'est exactement le potager familial.\n\nLe réducteur est le point sur lequel Eurosystems a mis le soin, et c'est le bon : c'est la pièce qui lâche en premier sur les motobineuses bon marché. Les fraises sont dimensionnées pour ne pas se bourrer en terre humide.\n\nMoteur Loncin OHV 123 cm³, 4 CV, démarrage par lanceur à rappel. Terrains souples, surface conseillée jusqu'à 30 m². Fabriquée en Italie.",
                'price' => 248.00,
                'compare_at_price' => 310.00,
                'colors' => null,
                'stock' => 12,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-18795.jpg', 'gb-18795-2.jpg', 'gb-18795-3.jpg', 'gb-18795-4.jpg', 'gb-18795-5.jpg'],
            ],
            [
                'category_id' => $motoculture->id,
                'name' => 'Sbaraglia Forza 24 — Débroussailleuse à batterie 2x21V 5,2 Ah',
                'description' => "2,6 kg : parmi les plus légères de sa catégorie, et c'est tout l'argument. Une débroussailleuse que l'on peut tenir une heure sans harnais change la nature du travail — on fait les finitions au lieu de les remettre à plus tard.\n\nLe moteur brushless de 500 W ne s'entretient pas et tire moins sur les batteries. La tige en aluminium de 25 mm garde la rigidité malgré la légèreté : elle ne fléchit pas quand on attaque une touffe dense.\n\nMoteur brushless 500 W. Deux batteries lithium 21 V / 5,2 Ah incluses. Tige aluminium Ø 25 mm. Poids 2,6 kg. Poignée ergonomique simple.",
                'price' => 311.94,
                'compare_at_price' => 389.92,
                'colors' => null,
                'stock' => 10,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-19917.png', 'gb-19917-2.jpg', 'gb-19917-3.jpg', 'gb-19917-4.jpg', 'gb-19917-5.jpg'],
            ],
            [
                'category_id' => $motoculture->id,
                'name' => 'EuroMech ZHO 50C — Débroussailleuse à dos essence 4 temps Honda GX50',
                'description' => "Le moteur passe sur le dos : le bras ne porte plus que la tige et la tête. C'est la solution pour les longues séances et pour les terrains escarpés, où une débroussailleuse classique devient rapidement épuisante à tenir en équilibre.\n\nLe Honda GX50 est un 4 temps : pas de mélange à préparer, moins de fumée, moins de bruit et un couple disponible plus bas dans les tours qu'un 2 temps équivalent. C'est le moteur que l'on garde dix ans.\n\nMoteur Honda GX50, 47,9 cm³, 4 temps, refroidissement à air, monocylindre. Puissance maximale 1,47 kW (2 CV) à 7 000 tr/min, couple 2,2 Nm à 5 500 tr/min. Portage dorsal.",
                'price' => 368.30,
                'compare_at_price' => 460.38,
                'colors' => null,
                'stock' => 8,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-21240.png', 'gb-21240-2.jpg', 'gb-21240-3.jpg', 'gb-21240-4.jpg', 'gb-21240-5.jpg'],
            ],
            [
                'category_id' => $motoculture->id,
                'name' => 'Kawasaki TJ53E I — Débroussailleuse thermique multifonction arbre Attila',
                'description' => "Une seule machine, trois outils : débroussailleuse au fil ou au disque, perche élagueuse avec la scie à chaîne fournie, taille-haie avec la tête correspondante. Pour une propriété où l'on fait un peu de tout et pas assez de chaque, c'est le bon calcul — un moteur à entretenir au lieu de trois.\n\nLa rallonge fournie ajoute 75 cm de portée à chaque accessoire, ce qui rend la version élagueuse réellement utilisable en hauteur plutôt que symbolique.\n\nMoteur Kawasaki TJ 53 E, arbre Attila. Accessoires fournis : tête débroussailleuse fil et disque, scie à chaîne d'élagage, taille-haie, rallonge de 75 cm. Usage professionnel.",
                'price' => 417.42,
                'compare_at_price' => 521.77,
                'colors' => null,
                'stock' => 7,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-19945.png', 'gb-19945-2.jpg', 'gb-19945-3.jpg', 'gb-19945-4.jpg', 'gb-19945-5.jpg'],
            ],
            [
                'category_id' => $motoculture->id,
                'name' => 'BullMach GEO 50 BS — Motoculteur essence Briggs & Stratton 7 CV',
                'description' => "Il n'entre pas très profond, mais il émiette la terre plus finement que n'importe quelle motobineuse — c'est exactement ce que l'on veut avant un semis. Pour préparer un lit de semence sur un sol déjà travaillé, c'est l'outil juste.\n\nLes grandes roues et les fraises à trois houes surdimensionnées suppriment l'effet de saut qui rend les petites machines pénibles. L'embrayage inversé coupe l'entraînement dès qu'on lâche : sur une machine qui tire, c'est la sécurité qui compte.\n\nMoteur Briggs & Stratton CR950, essence 4 temps, 208 cm³, 7 CV. Fraises à 3 houes surdimensionnées, grandes roues motrices. Embrayage inversé de sécurité. Carter arrière et flancs réglables en hauteur. Pour sols meubles et non caillouteux.",
                'price' => 509.10,
                'compare_at_price' => 636.37,
                'colors' => null,
                'stock' => 6,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-19501.png', 'gb-19501-2.jpg', 'gb-19501-3.jpg', 'gb-19501-4.jpg', 'gb-19501-5.jpg'],
            ],
            [
                'category_id' => $motoculture->id,
                'name' => 'Italian Power RG6.5-130 — Motobineuse essence 13 CV largeur 141 cm',
                'description' => "Cent quatre kilos, et c'est voulu : le poids est ce qui fait entrer les fraises dans une terre jamais défrichée. Sur un terrain dur ou en friche, une machine légère saute et gratte la surface — celle-ci descend à 30 cm.\n\nCent quarante et un centimètres de largeur de travail avec huit fraises : on reprend une grande parcelle en un nombre de passages raisonnable. Deux vitesses avant et une marche arrière donnent le contrôle qu'exige une machine de ce poids.\n\nMoteur Rato R389, 4 temps, 389 cm³, 6,5 kW (13 CV). 8 fraises de 33 cm de diamètre, largeur de travail 141 cm, profondeur 30 cm. 2 vitesses avant et 1 arrière, transmission à engrenages à bain d'huile. Poids 104 kg. Mancherons réglables en hauteur.",
                'price' => 891.54,
                'compare_at_price' => 1114.42,
                'colors' => null,
                'stock' => 4,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-19182.png', 'gb-19182-2.jpg', 'gb-19182-3.jpg', 'gb-19182-4.jpg', 'gb-19182-5.jpg'],
            ],
            [
                'category_id' => $motoculture->id,
                'name' => 'Eurosystems P55 — Débroussailleuse à roues essence Honda GCVX 170',
                'description' => "Une débroussailleuse qui roule au lieu d'être portée : on la pousse comme une tondeuse et elle avale une végétation dense et irrégulière sur 60 cm de large. Pour une friche, une prairie ou un terrain rustique, c'est infiniment moins fatigant qu'une débroussailleuse à dos.\n\nLa tête accepte quatre sorties de fil nylon de 3 mm et jusqu'à deux bobines de 7,5 m : on ne s'arrête pas toutes les dix minutes pour recharger, ce qui est le défaut habituel de ce type de machine.\n\nMoteur Honda GCVX 170. Largeur de coupe 60 cm. Tête à 4 sorties pour fil nylon 3 mm, jusqu'à 2 rouleaux de 7,5 m. Accessoire conçu pour la machine multifonction P55 EVO. Protections métal et plastique, structure compacte pour usage intensif.",
                'price' => 1251.64,
                'compare_at_price' => 1564.55,
                'colors' => null,
                'stock' => 3,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-21471.png', 'gb-21471-2.jpg', 'gb-21471-3.jpg', 'gb-21471-4.jpg', 'gb-21471-5.jpg'],
            ],
            [
                'category_id' => $motoculture->id,
                'name' => 'Lampacrescia MGM Boxer — Motoculteur essence Loncin 10 CV',
                'description' => "Un vrai motoculteur, pas une motobineuse : la prise de force indépendante permet d'atteler autre chose que la fraise — charrue, remorque, barre de coupe. C'est une machine que l'on garde et que l'on équipe au fil des années.\n\nLes mancherons se retournent sur 180° et se règlent en hauteur comme latéralement : on travaille dans un sens, on attelle dans l'autre, et on adapte la position à sa taille. L'embrayage à quatre disques secs encaisse.\n\nMoteur Loncin G270F, essence, 10 CV. Prise de force indépendante à 1 vitesse. Embrayage multiple à 4 disques secs. Boîte à 4 vitesses : 2 avant et 2 arrière, axe rigide. Mancherons amortis réversibles à 180°, réglables en hauteur et latéralement.",
                'price' => 2151.58,
                'compare_at_price' => 2689.47,
                'colors' => null,
                'stock' => 2,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-19389.png', 'gb-19389-2.jpg', 'gb-19389-3.jpg', 'gb-19389-4.jpg', 'gb-19389-5.jpg'],
            ],
            [
                'category_id' => $motoculture->id,
                'name' => 'Lampacrescia MGM Castoro Super — Motoculteur diesel Kohler 12 CV',
                'description' => "Le diesel, sur un motoculteur, se justifie par deux choses : le couple à bas régime, qui fait avancer la fraise dans une terre lourde sans effort, et la consommation, qui compte quand la machine travaille des journées entières. C'est le haut du rayon motoculture.\n\nSept rapports — quatre avant, trois arrière — avec inverseur : on choisit vraiment son allure selon l'outil attelé et la nature du sol, au lieu de composer avec deux vitesses. La fraise de 80 cm couvre large.\n\nMoteur diesel Kohler 441 cm³, 12 CV. Boîte à 7 vitesses (4 avant, 3 arrière), axe rigide avec inverseur. Embrayage multiple à 4 disques secs. Fraise de 80 cm. Mancherons amortis réversibles à 180°, réglables en hauteur et latéralement.",
                'price' => 5205.94,
                'compare_at_price' => 6507.42,
                'colors' => null,
                'stock' => 1,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-19319.png', 'gb-19319-2.jpg', 'gb-19319-3.jpg', 'gb-19319-4.jpg', 'gb-19319-5.jpg'],
            ],

            // ================================================================= BOIS & CHAUFFAGE
            [
                'category_id' => $bois->id,
                'name' => 'Bûches de feuillus français 50 cm — colis de 15 kg',
                'description' => "Le petit colis que l'on prend pour le week-end, ou pour vérifier que ces bûches conviennent à son foyer avant d'en commander un stère. Prêtes à brûler : elles s'allument vite et donnent de la chaleur tout de suite, sans le sifflement d'un bois encore vert.\n\nC'est un mélange de bois durs, donc les bûches ne se ressemblent pas d'un colis à l'autre — l'aspect et le calibre varient, la qualité de chauffe non.\n\n100 % feuillus durs : chêne, hêtre, charme, frêne. Bois français, séchage d'environ 18 mois. Longueur 50 cm environ, 1 à 3 kg par bûche. Colis de 15 kg. Pour cheminées, poêles et fours à bois. Pas de livraison en Corse ni sur les îles.",
                'price' => 29.90,
                'compare_at_price' => 39.90,
                'colors' => null,
                'stock' => 120,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-29684.webp', 'gb-29684-2.webp', 'gb-29684-3.webp', 'gb-29684-4.webp'],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Bûches de chêne vert — carton de 40 kg',
                'description' => "Le chêne vert brûle lentement et chaud : c'est le bois que l'on met quand on veut que le feu tienne la soirée sans y revenir toutes les demi-heures. Pouvoir calorifique élevé, braise longue.\n\nLivré en carton recyclé plutôt qu'en sac plastique, ce qui change la manutention — le carton se porte, se range dans un cellier et se recycle avec le reste.\n\n100 % chêne vert issu de taille contrôlée, séché et prêt à l'emploi. Carton de 40 kg. Pour cheminées, poêles, cassettes et chaudières. Produit d'Espagne.",
                'price' => 78.94,
                'compare_at_price' => 95.94,
                'colors' => null,
                'stock' => 60,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-29671.webp', 'gb-29671-2.webp', 'gb-29671-3.webp', 'gb-29671-4.webp'],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Bûches 40 cm — 1,6 stère à sécher',
                'description' => "Du bois à acheter maintenant pour brûler l'hiver prochain : à 23 % d'humidité, il n'est pas prêt et ne doit pas l'être. C'est la manière la moins chère de se chauffer, à condition d'avoir l'abri qui va avec.\n\nÀ stocker sous abri surélevé et ventilé, dix-huit mois au minimum. Un bois rentré à 23 % et brûlé tout de suite encrasse le conduit et chauffe deux fois moins — la patience est ici un vrai poste d'économie.\n\n90 % essences dures (hêtre, chêne, bouleau, frêne) et 10 % essences diverses. Longueur 40 cm, volume 1,6 stère. Humidité 23 % : à sécher avant emploi, 18 mois minimum sous abri surévelé et ventilé. Palette de 550 kg, 110 x 100 x 120 cm.",
                'price' => 149.00,
                'compare_at_price' => 201.00,
                'colors' => null,
                'stock' => 30,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-29629.webp'],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Granulés Pellet Limouzi DIN Plus — palette de 66 sacs (990 kg)',
                'description' => "Des granulés issus de la scierie du fabricant, donc d'une sciure fraîche et constante : c'est ce qui explique le taux de poussière inférieur à 0,4 % et le fait que le poêle s'encrasse peu. Sur une saison entière, la différence se voit dans le cendrier.\n\nMoins de 8 % d'humidité et 4,6 à 5 kWh/kg : la combustion est lente et complète, on consomme moins de sacs pour la même chaleur. C'est le bon rapport qualité-prix de la gamme granulés.\n\n100 % résineux, diamètre 6 mm. Certifications DIN Plus et PEFC. Pouvoir calorifique 4,6 à 5 kWh/kg. Humidité < 8 %, cendres < 0,5 %, poussières < 0,4 %. Palette de 66 sacs de 15 kg, soit 990 kg. Origine Belgique. Livraison sur rendez-vous, dépose au pied de la propriété sur sol stabilisé.",
                'price' => 161.99,
                'compare_at_price' => 230.00,
                'colors' => null,
                'stock' => 40,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-9177.jpg'],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Bûches fendues 50 cm — box de 1,25 stère',
                'description' => "Du bois sec, fendu, livré en box : celui que l'on brûle le soir même. Les 50 cm conviennent aux foyers ouverts et aux grands inserts ; pour un poêle, mieux vaut les longueurs courtes.\n\nUne précision qui évite les mauvaises surprises : un stère de 50 cm occupe environ 0,80 m³ rangé, contre 0,60 m³ en 33 cm. Le bois court s'empile mieux, le volume apparent baisse, mais la quantité de bois est la même — comparez les stères, pas les mètres cubes.\n\nMélange de feuillus : chêne, hêtre, frêne, châtaignier. Longueur 50 cm, bois fendu. Volume 1,05 m³, soit 1,25 stère. Bois sec, prêt à l'emploi. Livré sur palette.",
                'price' => 189.00,
                'compare_at_price' => 229.00,
                'colors' => null,
                'stock' => 28,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-29689.webp'],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Granulés TotalEnergies Premium — palette de 66 sacs (990 kg)',
                'description' => "Des granulés premium à additif 100 % naturel, avec une densité apparente supérieure à 630 kg/m³ : plus le granulé est dense, moins il se casse dans la vis sans fin et moins il fait de fines. C'est ce qui distingue un pellet premium d'un pellet standard.\n\nMoins de 8 % d'humidité et au moins 4,8 kWh/kg : la vitre reste propre plus longtemps et le cendrier se vide moins souvent. Sur une saison de chauffe, c'est du temps gagné autant que des sacs économisés.\n\n100 % résineux. Pouvoir calorifique inférieur ≥ 4,8 kWh/kg. Humidité ≤ 8 %, cendres 0,5 %, fines ≤ 0,5 %. Densité apparente ≥ 630 kg/m³. Additif 100 % naturel ≤ 0,8 %. Palette de 66 sacs de 15 kg, soit 990 kg. Pour poêle, insert ou chaudière à granulés.",
                'price' => 223.89,
                'compare_at_price' => 373.08,
                'colors' => null,
                'stock' => 35,
                'is_new' => false,
                'is_bestseller' => true,
                'images' => ['gb-9315.jpg'],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Granulés Pellet Helios DIN Plus / EN Plus A1 — palette de 65 sacs (975 kg)',
                'description' => "Le sac est transparent, et ce n'est pas un détail : on voit la couleur très claire des granulés et le peu de poussière au fond avant même d'ouvrir. Sur un produit où la qualité se juge à l'usage, pouvoir vérifier à l'œil change la donne.\n\nDouble certification DIN Plus et EN Plus A1, plus de 4,7 kWh/kg : c'est un granulé universel, qui convient aussi bien à un poêle qu'à une chaudière, à un prix contenu.\n\n100 % résineux, diamètre 6 mm. Certifications DIN Plus et EN Plus A1. Pouvoir calorifique > 4,7 kWh/kg. Humidité < 10 %, cendres < 0,7 %, poussières < 0,5 %. Palette de 65 sacs de 15 kg, soit 975 kg. Origine Belgique.",
                'price' => 265.00,
                'compare_at_price' => 310.00,
                'colors' => null,
                'stock' => 32,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-8902.jpeg'],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Granulés B.Pellet feuillus EN Plus A1 — palette de 72 sacs (1080 kg)',
                'description' => "La plus grosse palette du rayon : 1 080 kg, soit une saison de chauffe complète pour un poêle. C'est le format qui fait baisser le prix au kilo et qui évite de repasser commande en janvier, au moment précis où tout le monde le fait et où les délais s'allongent.\n\nCertifiés EN Plus A1 avec une durabilité mécanique supérieure à 98 % : le granulé arrive entier au bout du transport et de la vis sans fin, au lieu de se réduire en fines qui bourrent l'alimentation.\n\nCertification EN Plus A1. Pouvoir calorifique net ≥ 16,5 MJ/kg. Humidité ≤ 10 %, cendres ≤ 0,7 %, fines ≤ 0,5 %. Durabilité mécanique ≥ 98 %. Densité apparente ≥ 600 kg/m³. Température de fusion des cendres ≥ 1 200 °C. Palette de 72 sacs de 15 kg, soit 1 080 kg. Origine Belgique. À stocker au sec : un granulé humide gonfle et bloque la vis du poêle.",
                'price' => 302.99,
                'compare_at_price' => 467.28,
                'colors' => null,
                'stock' => 22,
                'is_new' => true,
                'is_bestseller' => false,
                'images' => ['gb-9323.jpg'],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Palette de bûches densifiées 100 % naturelles',
                'description' => "Quatre fois moins encombrantes que du bois traditionnel pour trois fois plus d'énergie : c'est l'argument décisif quand on n'a pas d'abri à bûches. Une palette de densifiées tient dans un coin de garage là où un stère demande un appentis.\n\nFabriquées par compression à haute pression de sciures et de copeaux non traités, sans liant ni colle. Elles ne poudrent pas, ne salissent pas les mains et laissent très peu de cendres — on les manipule en tenue de ville.\n\n100 % naturelles, issues du recyclage de connexes de scierie, compactées à haute pression. Qualité contrôlée en laboratoire CERIC. Livrées sur palette.",
                'price' => 549.99,
                'compare_at_price' => 619.00,
                'colors' => null,
                'stock' => 15,
                'is_new' => false,
                'is_bestseller' => false,
                'images' => ['gb-7427.jpg', 'gb-7427-2.jpg'],
            ],
            [
                'category_id' => $bois->id,
                'name' => 'Poêle à bois Godin Carvin 11 kW — fonte émaillée sable',
                'description' => "Un corps de chauffe en fonte, et non en acier : la fonte monte moins vite mais restitue la chaleur longtemps après que le feu est tombé. C'est ce qui fait qu'une pièce reste tiède au petit matin.\n\nOnze kilowatts et des bûches de 65 cm : il chauffe une grande pièce, voire un rez-de-chaussée ouvert, et il accepte les longueurs que l'on trouve couramment sans avoir à recouper. Le chargement se fait par l'avant ou par le côté, selon la place disponible autour.\n\nPuissance 11 kW, rendement 76,2 %. Bûches jusqu'à 65 cm. Habillage fonte émaillée sable, corps de chauffe fonte. Chargement avant ou latéral, régulation thermostatique. Raccordement arrière ou dessus, buse Ø 180 mm, hauteur d'axe 720 mm. Dimensions 75 x 85 x 51 cm, poids 188 kg. Norme NF EN 13240, Flamme Verte 7 étoiles, label énergie B. CO 0,09 %, poussières 31 mg/Nm³.",
                'price' => 2300.00,
                'compare_at_price' => 2500.00,
                'colors' => null,
                'stock' => 4,
                'is_new' => true,
                'is_bestseller' => true,
                'images' => ['gb-7466.jpg'],
            ],
        ];

        $seeded = [];

        foreach ($products as $data) {
            $images = $data['images'];
            unset($data['images']);

            $slug = Str::slug($data['name']);
            $seeded[] = $slug;

            $product = Product::query()->updateOrCreate(
                ['slug' => $slug],
                $data + ['slug' => $slug, 'is_active' => true]
            );

            $product->images()->delete();

            foreach ($images as $position => $file) {
                $path = 'products/'.$file;

                if (! Storage::disk('public')->exists($path)) {
                    Storage::disk('public')->put(
                        $path,
                        file_get_contents(__DIR__.'/assets/products/'.$file)
                    );
                }

                ProductImage::create([
                    'product_id' => $product->id,
                    'path' => $path,
                    'position' => $position,
                ]);
            }
        }

        // Products from an earlier version of this catalogue — including the whole furniture
        // range this shop sold before the change of trade — would otherwise survive re-seeding
        // and show up alongside the current selection. Order history is unaffected: order_items
        // snapshots product_name and unit_price, and its product_id is nullOnDelete.
        Product::query()
            ->whereNotIn('slug', $seeded)
            ->each(function (Product $product) {
                $product->images()->delete();
                $product->delete();
            });
    }
}
